In [1]:
import os
import time
import random
import warnings

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from lxml import etree # type: ignore <- pylance milně hlásí chybu
from pathlib import Path
import time
import sys
import polars as pl
import polars.selectors as cs
import json
import pickle
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from ydata_profiling import ProfileReport

from utils import *
from schemas import *
from processing import *

pl.Config.set_tbl_cols(-1)
os.chdir(r'E:\CVUT_BAP')
SEED=42

# Načtení dat

In [2]:
df = pl.read_parquet('kod/data/prohlidky_vozidel_stk_a_sme/parquet/prohlidky', schema=prohlidky_schema)#.sample(fraction=1.0, shuffle=True, seed=SEED)
short_display(df)
display_counts(df)

(48338032, 52)

,CisloProtokolu,DatumProhlidky,DruhProhlidky,RozsahProhlidky,Prohlidka_OdpovednaOsoba,Prohlidka_Stanice_Cislo,Prohlidka_Stanice_Kraj,Prohlidka_Stanice_ORP,Prohlidka_Stanice_Obec,Prohlidka_Zahajeni,...,Adr_KodCisterny,Adr_CisloOsvedceni,Adr_ZavadyText,Adr_Poznamka,Tsk_OdpovednaOsoba,Vysledek_Odometr,Vysledek_Poznamka,Vysledek_DatumPristiProhlidky,Vysledek_NalepkaVylepena,Vysledek_Celkovy
0,CZ-520406-19-01-0001,2019-01-01,Pravidelná,None,16835,520406,Středočeský kraj,Kolín,Žabonosy,2019-01-01T15:21:49.0770000+01:00,...,None,None,None,None,None,309068,None,2021-01-01,None,1
1,CZ-420930-19-01-0001,2019-01-01,Pravidelná,None,43281,420930,Středočeský kraj,Říčany,Říčany,2019-01-01T14:35:04.4400000+01:00,...,None,None,None,None,None,169952,None,2021-01-01,None,1
2,CZ-6711-20-51-9008,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
3,CZ-6711-20-51-9009,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
4,CZ-6711-20-51-9015,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
5,CZ-6711-20-51-9010,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
6,CZ-6711-20-51-9011,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
7,CZ-6711-20-51-9012,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
8,CZ-6711-20-51-9013,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
9,CZ-6711-20-51-9014,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
10,CZ-6711-20-51-9001,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
11,CZ-6711-20-51-9002,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
12,CZ-6711-20-51-9004,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
13,CZ-6711-20-51-9005,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
14,CZ-6711-20-51-9006,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
15,CZ-6711-20-51-9003,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
16,CZ-6711-20-51-9007,2020-01-01,Pravidelná,Plný,28247,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2020-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-01,true,1
17,CZ-3724-20-01-0001,2020-01-01,Evidencní kontrola,Plný,355,3724,Kraj Vysočina,Žďár nad Sázavou,Žďár nad Sázavou,2020-01-01T17:13:47.4830000+01:00,...,None,None,None,None,None,None,None,None,false,1
18,CZ-3830-20-01-0001,2020-01-01,Evidencní kontrola,Plný,515,3830,Moravskoslezský kraj,Krnov,Krnov,2020-01-01T14:52:29.1030000+01:00,...,None,None,None,None,None,110160,None,None,false,1
19,CZ-7714-22-01-0001,2022-01-01,Technická silniční kontrola,Částečný,38155,7714,Olomoucký kraj,Olomouc,Olomouc,2022-01-01T20:09:21.1630000+01:00,...,None,None,None,None,38155,1590260,None,None,false,1
20,CZ-480811-23-01-0001,2023-01-01,Pravidelná,None,36479,480811,Olomoucký kraj,Přerov,Kojetín,2023-01-01T12:21:49.8570000+01:00,...,None,None,None,None,None,241379,None,2025-01-01,None,1
21,CZ-420221-23-01-0004,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T17:25:41.6570000+01:00,...,None,None,None,None,None,65923,None,2025-01-01,None,1
22,CZ-420221-23-01-0001,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:05:05.4600000+01:00,...,None,None,None,None,None,264005,None,2025-01-01,None,1
23,CZ-420221-23-01-0003,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:56:47.6530000+01:00,...,None,None,None,None,None,146446,None,2025-01-01,None,1
24,CZ-170901-23-01-0001,2023-01-01,Pravidelná,None,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:23:52.2530000+01:00,...,None,None,None,None,None,237886,None,2025-01-01,None,1
25,CZ-170901-23-01-0002,2023-01-01,Pravidelná,None,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:40:36.1970000+01:00,...,None,None,None,None,None,210028,None,2025-01-01,None,1
26,CZ-6711-24-51-9516,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
27,CZ-6711-24-51-9517,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
28,CZ-6711-24-51-9518,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
29,CZ-6711-24-51-9519,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
30,CZ-6711-24-51-9520,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
31,CZ-6711-24-51-9521,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
32,CZ-6711-24-51-9522,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
33,CZ-6711-24-51-9514,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2024-01-31,false,2
34,CZ-6711-24-51-9515,2024-01-01,Pred registrací,Plný,82219,6711,Kraj Vysočina,Jihlava,Dolní Cerekev,2024-01-01T00:00:00.0000000+01:00,...,None,None,None,None,None,None,None,2028-01-01,false,1
35,CZ-7719-24-01-0003,2024-01-01,Technická silniční kontrola,Částečný,29999,7719,Karlovarský kraj,Karlovy Vary,Karlovy Vary,2024-01-01T23:00:40.3470000+01:00,...,None,None,None,None,29999,None,None,None,false,1
36,CZ-3316-24-01-0003,2024-01-01,Evidencní kontrola,Plný,9903,3316,Kraj Vysočina,Humpolec,Humpolec,2024-01-01T12:09:11.5130000+01:00,...,None,None,None,None,None,401508,None,None,false,1
37,CZ-3316-24-01-0004,2024-01-01,Pravidelná,Plný,9903,3316,Kraj Vysočina,Humpolec,Humpolec,2024-01-01T12:21:45.3800000+01:00,...,None,None,None,None,None,401508,None,2026-01-01,false,1
38,CZ-7719-24-01-0004,2024-01-01,Technická silniční kontrola,Částečný,29999,7719,Karlovarský kraj,Karlovy Vary,Karlovy Vary,2024-01-01T23:00:40.3470000+01:00,...,None,None,None,None,29999,265057,None,None,false,1
39,CZ-520406-24-01-0001,2024-01-01,Pravidelná,None,1308,520406,Středočeský kraj,Kolín,Žabonosy,2024-01-01T11:30:09.4530000+01:00,...,None,None,None,None,None,237115,None,2026-01-01,None,1
40,CZ-480811-24-01-0001,2024-01-01,Pravidelná,None,36479,480811,Olomoucký kraj,Přerov,Kojetín,2024-01-01T16:21:48.9530000+01:00,...,None,None,None,None,None,263886,None,2026-01-01,None,1
41,CZ-571206-24-01-0001,2024-01-01,Pravidelná,None,58519,571206,Jihomoravský kraj,Slavkov u Brna,Slavkov u Brna,2024-01-01T17:03:58.7070000+01:00,...,None,None,None,None,None,142630,None,2026-01-01,None,1
42,CZ-420221-25-01-0004,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:22:17.4230000+01:00,...,None,None,None,None,None,166686,None,2027-01-01,None,1
43,CZ-420221-25-01-0005,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:36:09.3600000+01:00,...,None,None,None,None,None,268022,None,None,None,3
44,CZ-420221-25-01-0001,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T17:03:46.4900000+01:00,...,None,None,None,None,None,268009,Chyba přenosu dat z Teasu do CIS.,None,None,3
45,CZ-420221-25-01-0003,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:11:21.9530000+01:00,...,None,None,None,None,None,244651,None,2027-01-01,None,1
46,CZ-7701-25-01-0001,2025-01-01,Technická silniční kontrola,Částečný,79325,7701,Hlavní město Praha,Hlavní město Praha,Praha,2025-01-01T11:40:54.8100000+01:00,...,None,None,None,None,79325,None,None,None,false,2
47,CZ-420221-25-01-0002,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T17:30:38.6070000+01:00,...,None,None,None,None,None,268009,None,None,None,3
48,CZ-7702-25-01-0001,2025-01-01,Technická silniční kontrola,Částečný,98137,7702,Jihočeský kraj,České Budějovice,České Budějovice,2025-01-01T17:10:45.8830000+01:00,...,None,None,None,None,98137,None,None,None,false,2
49,CZ-7707-26-01-0001,2026-01-01,Technická silniční kontrola,Částečný,98853,7707,Moravskoslezský kraj,Ostrava,Ostrava,2025-12-31T22:20:28.7930000+01:00,...,None,None,None,None,98853,385421,None,None,false,1

                                                        0
CisloProtokolu                        48338032 / 48338032
DatumProhlidky                        48338032 / 48338032
DruhProhlidky                         48338032 / 48338032
RozsahProhlidky                       29226013 / 48338032
Prohlidka_OdpovednaOsoba              48338032 / 48338032
Prohlidka_Stanice_Cislo               48338032 / 48338032
Prohlidka_Stanice_Kraj                48338032 / 48338032
Prohlidka_Stanice_ORP                 48333234 / 48338032
Prohlidka_Stanice_Obec                48333234 / 48338032
Prohlidka_Zahajeni                    48338032 / 48338032
Prohlidka_Ukonceni                    48338032 / 48338032
AdministrativniOprava_CisloProtokolu    227521 / 48338032
AdministrativniOprava_DatumProhlidky    227521 / 48338032
Vozidlo_Vin                           48338032 / 48338032
Vozidlo_Druh                          48336741 / 48338032
Vozidlo_Kategorie                     48337969 / 48338032
Vozidlo_Provedeni                     25210003 / 48338032
Vozidlo_Znacka                        48329905 / 48338032
Vozidlo_ObchodniOznaceni              48329905 / 48338032
Vozidlo_TypMotoru                     46709093 / 48338032
Registrace_DatumPrvni                 48135625 / 48338032
Registrace_Stat                       48338027 / 48338032
Registrace_CisloDokladu               48082172 / 48338032
Emise_CisloProtokolu                  20060291 / 48338032
Emise_DatumProhlidky                  20060291 / 48338032
Emise_Stanice_Cislo                   20060291 / 48338032
Emise_Zahajeni                        19886081 / 48338032
Emise_Ukonceni                        19886081 / 48338032
Emise_OdpovednaOsoba                  20060291 / 48338032
Emise_ZakladniPalivo                  20060291 / 48338032
Emise_AlternativniPalivo                456437 / 48338032
Emise_EmisniSystem                    20060291 / 48338032
Emise_VyrobceMotoru                    1825729 / 48338032
Emise_CisloMotoru                      2025230 / 48338032
Technicka_Zahajeni                    28678810 / 48338032
Technicka_Ukonceni                    28678603 / 48338032
Technicka_OdpovednaOsoba              29030534 / 48338032
Adr_Zahajeni                             34492 / 48338032
Adr_Ukonceni                             34492 / 48338032
Adr_OdpovednaOsoba                       35134 / 48338032
Adr_Platnost_Periodicka                  16462 / 48338032
Adr_Platnost_Meziperiodicka              16133 / 48338032
Adr_KodCisterny                          24329 / 48338032
Adr_CisloOsvedceni                       35056 / 48338032
Adr_ZavadyText                            1575 / 48338032
Adr_Poznamka                             12873 / 48338032
Tsk_OdpovednaOsoba                      147458 / 48338032
Vysledek_Odometr                      45893682 / 48338032
Vysledek_Poznamka                      1048671 / 48338032
Vysledek_DatumPristiProhlidky         42189108 / 48338032
Vysledek_NalepkaVylepena              29226013 / 48338032
Vysledek_Celkovy                      48250461 / 48338032

# Výběr relevantních sloupců a řádků

In [3]:
df = df.filter(pl.col('Emise_CisloProtokolu').is_not_null())
describe(df)

(20060291, 52)

,CisloProtokolu,DatumProhlidky,DruhProhlidky,RozsahProhlidky,Prohlidka_OdpovednaOsoba,Prohlidka_Stanice_Cislo,Prohlidka_Stanice_Kraj,Prohlidka_Stanice_ORP,Prohlidka_Stanice_Obec,Prohlidka_Zahajeni,...,Adr_KodCisterny,Adr_CisloOsvedceni,Adr_ZavadyText,Adr_Poznamka,Tsk_OdpovednaOsoba,Vysledek_Odometr,Vysledek_Poznamka,Vysledek_DatumPristiProhlidky,Vysledek_NalepkaVylepena,Vysledek_Celkovy
0,CZ-520406-19-01-0001,2019-01-01,Pravidelná,None,16835,520406,Středočeský kraj,Kolín,Žabonosy,2019-01-01T15:21:49.0770000+01:00,...,None,None,None,None,None,309068,None,2021-01-01,None,1
1,CZ-420930-19-01-0001,2019-01-01,Pravidelná,None,43281,420930,Středočeský kraj,Říčany,Říčany,2019-01-01T14:35:04.4400000+01:00,...,None,None,None,None,None,169952,None,2021-01-01,None,1
2,CZ-480811-23-01-0001,2023-01-01,Pravidelná,None,36479,480811,Olomoucký kraj,Přerov,Kojetín,2023-01-01T12:21:49.8570000+01:00,...,None,None,None,None,None,241379,None,2025-01-01,None,1
3,CZ-420221-23-01-0004,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T17:25:41.6570000+01:00,...,None,None,None,None,None,65923,None,2025-01-01,None,1
4,CZ-420221-23-01-0001,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:05:05.4600000+01:00,...,None,None,None,None,None,264005,None,2025-01-01,None,1
5,CZ-420221-23-01-0003,2023-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:56:47.6530000+01:00,...,None,None,None,None,None,146446,None,2025-01-01,None,1
6,CZ-170901-23-01-0001,2023-01-01,Pravidelná,None,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:23:52.2530000+01:00,...,None,None,None,None,None,237886,None,2025-01-01,None,1
7,CZ-170901-23-01-0002,2023-01-01,Pravidelná,None,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:40:36.1970000+01:00,...,None,None,None,None,None,210028,None,2025-01-01,None,1
8,CZ-520406-24-01-0001,2024-01-01,Pravidelná,None,1308,520406,Středočeský kraj,Kolín,Žabonosy,2024-01-01T11:30:09.4530000+01:00,...,None,None,None,None,None,237115,None,2026-01-01,None,1
9,CZ-480811-24-01-0001,2024-01-01,Pravidelná,None,36479,480811,Olomoucký kraj,Přerov,Kojetín,2024-01-01T16:21:48.9530000+01:00,...,None,None,None,None,None,263886,None,2026-01-01,None,1
10,CZ-571206-24-01-0001,2024-01-01,Pravidelná,None,58519,571206,Jihomoravský kraj,Slavkov u Brna,Slavkov u Brna,2024-01-01T17:03:58.7070000+01:00,...,None,None,None,None,None,142630,None,2026-01-01,None,1
11,CZ-420221-25-01-0004,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:22:17.4230000+01:00,...,None,None,None,None,None,166686,None,2027-01-01,None,1
12,CZ-420221-25-01-0005,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:36:09.3600000+01:00,...,None,None,None,None,None,268022,None,None,None,3
13,CZ-420221-25-01-0001,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T17:03:46.4900000+01:00,...,None,None,None,None,None,268009,Chyba přenosu dat z Teasu do CIS.,None,None,3
14,CZ-420221-25-01-0003,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T18:11:21.9530000+01:00,...,None,None,None,None,None,244651,None,2027-01-01,None,1
15,CZ-420221-25-01-0002,2025-01-01,Pravidelná,None,44365,420221,Středočeský kraj,Beroun,Bavoryně,2025-01-01T17:30:38.6070000+01:00,...,None,None,None,None,None,268009,None,None,None,3
16,CZ-420107-19-02-0012,2019-02-01,Pravidelná,None,50929,420107,Středočeský kraj,Benešov,Benešov,2019-02-01T16:22:59.1170000+01:00,...,None,None,None,None,None,221599,None,2021-02-01,None,1
17,CZ-420620-19-02-0041,2019-02-01,Pravidelná,None,893,420620,Středočeský kraj,Mělník,Mělník,2019-02-01T16:15:02.5430000+01:00,...,None,None,None,None,None,71829,None,2021-02-01,None,1
18,CZ-430427-19-02-0019,2019-02-01,Pravidelná,None,308,430427,Kraj Vysočina,Pelhřimov,Pelhřimov,2019-02-01T16:11:03.0470000+01:00,...,None,None,None,None,None,208889,None,2021-02-01,None,1
19,CZ-410945-19-02-0039,2019-02-01,Pravidelná,None,36697,410945,Hlavní město Praha,Hlavní město Praha,Praha,2019-02-01T15:44:48.2600000+01:00,...,None,None,None,None,None,174667,None,2021-02-01,None,1
20,CZ-410617-19-02-0020,2019-02-01,Pravidelná,None,24287,410617,Hlavní město Praha,Hlavní město Praha,Praha,2019-02-01T16:19:46.6070000+01:00,...,None,None,None,None,None,293900,None,2021-02-01,None,1
21,CZ-540514-19-02-0127,2019-02-01,Pravidelná,None,34773,540514,Plzeňský kraj,Plzeň,Plzeň,2019-02-01T15:38:09.6570000+01:00,...,None,None,None,None,None,124001,None,2021-02-01,None,1
22,CZ-540514-19-02-0128,2019-02-01,Pravidelná,None,10599,540514,Plzeňský kraj,Plzeň,Plzeň,2019-02-01T16:15:38.4700000+01:00,...,None,None,None,None,None,160916,None,2021-02-01,None,1
23,CZ-480714-19-02-0036,2019-02-01,Pravidelná,None,41173,480714,Moravskoslezský kraj,Ostrava,Ostrava,2019-02-01T15:31:26.6830000+01:00,...,None,None,None,None,None,325265,None,2021-02-01,None,1
24,CZ-480756-19-02-0023,2019-02-01,Pravidelná,None,37311,480756,Moravskoslezský kraj,Ostrava,Ostrava,2019-02-01T16:21:29.4470000+01:00,...,None,None,None,None,None,148950,None,2021-02-01,None,1
25,CZ-560613-19-02-0024,2019-02-01,Pravidelná,None,21187,560613,Pardubický kraj,Pardubice,Pardubice,2019-02-01T16:25:57.5830000+01:00,...,None,None,None,None,None,187233,None,2021-02-01,None,1
26,CZ-440709-19-02-0045,2019-02-01,Pravidelná,None,2399,440709,Plzeňský kraj,Kralovice,Rybnice,2019-02-01T16:24:53.9030000+01:00,...,None,None,None,None,None,338837,None,2021-02-01,None,1
27,CZ-440709-19-02-0046,2019-02-01,Pravidelná,None,34841,440709,Plzeňský kraj,Kralovice,Rybnice,2019-02-01T16:56:25.9870000+01:00,...,None,None,None,None,None,171458,None,2021-02-01,None,1
28,CZ-440709-19-02-0044,2019-02-01,Pravidelná,None,2399,440709,Plzeňský kraj,Kralovice,Rybnice,2019-02-01T16:13:26.2100000+01:00,...,None,None,None,None,None,68863,None,2021-02-01,None,1
29,CZ-440709-19-02-0048,2019-02-01,Pravidelná,None,34841,440709,Plzeňský kraj,Kralovice,Rybnice,2019-02-01T17:54:49.8900000+01:00,...,None,None,None,None,None,70965,None,2021-02-01,None,1
30,CZ-550309-19-02-0015,2019-02-01,Pravidelná,None,2545,550309,Ústecký kraj,Chomutov,Spořice,2019-02-01T15:37:40.0000000+01:00,...,None,None,None,None,None,164283,None,2021-02-01,None,1
31,CZ-450620-19-02-0004,2019-02-01,Pravidelná,None,37581,450620,Ústecký kraj,Litoměřice,Liběšice,2019-02-01T16:25:46.2900000+01:00,...,None,None,None,None,None,243234,None,2021-02-01,None,1
32,CZ-460214-19-02-0056,2019-02-01,Pravidelná,None,47907,460214,Královéhradecký kraj,Hradec Králové,Hradec Králové,2019-02-01T19:15:01.3830000+01:00,...,None,None,None,None,None,205409,None,2021-02-01,None,1
33,CZ-460257-19-02-0025,2019-02-01,Pravidelná,None,43903,460257,Královéhradecký kraj,Hradec Králové,Třebechovice pod Orebem,2019-02-01T16:07:09.9300000+01:00,...,None,None,None,None,None,251122,None,2021-02-01,None,1
34,CZ-460257-19-02-0024,2019-02-01,Pravidelná,None,43903,460257,Královéhradecký kraj,Hradec Králové,Třebechovice pod Orebem,2019-02-01T15:52:34.6000000+01:00,...,None,None,None,None,None,214745,None,2021-02-01,None,1
35,CZ-460804-19-02-0006,2019-02-01,Pravidelná,None,40267,460804,Liberecký kraj,Turnov,Radostná pod Kozákovem,2019-02-01T16:09:34.1570000+01:00,...,None,None,None,None,None,163966,None,2021-02-01,None,1
36,CZ-480512-19-02-0029,2019-02-01,Pravidelná,None,45165,480512,Olomoucký kraj,Olomouc,Olomouc,2019-02-01T15:33:00.6900000+01:00,...,None,None,None,None,None,6280,None,2021-02-01,None,1
37,CZ-480512-19-02-0028,2019-02-01,Pravidelná,None,45165,480512,Olomoucký kraj,Olomouc,Olomouc,2019-02-01T15:13:49.0470000+01:00,...,None,None,None,None,None,66325,None,2021-02-01,None,1
38,CZ-480512-19-02-0032,2019-02-01,Pravidelná,None,45165,480512,Olomoucký kraj,Olomouc,Olomouc,2019-02-01T17:02:48.1130000+01:00,...,None,None,None,None,None,32169,None,2021-02-01,None,1
39,CZ-480512-19-02-0030,2019-02-01,Pravidelná,None,45165,480512,Olomoucký kraj,Olomouc,Olomouc,2019-02-01T16:11:53.8270000+01:00,...,None,None,None,None,None,None,None,2021-02-01,None,1
40,CZ-480512-19-02-0026,2019-02-01,Pravidelná,None,45165,480512,Olomoucký kraj,Olomouc,Olomouc,2019-02-01T14:54:56.2170000+01:00,...,None,None,None,None,None,209954,None,2021-02-01,None,1
41,CZ-480811-19-02-0010,2019-02-01,Pravidelná,None,36475,480811,Olomoucký kraj,Přerov,Kojetín,2019-02-01T16:21:21.4430000+01:00,...,None,None,None,None,None,171756,None,2021-02-01,None,1
42,CZ-520403-19-02-0024,2019-02-01,Pravidelná,None,462,520403,Středočeský kraj,Říčany,Kostelec nad Černými lesy,2019-02-01T16:00:45.3530000+01:00,...,None,None,None,None,None,193362,None,2021-02-01,None,1
43,CZ-420620-19-02-0042,2019-02-01,Pravidelná,None,893,420620,Středočeský kraj,Mělník,Mělník,2019-02-01T17:42:32.1530000+01:00,...,None,None,None,None,None,251535,None,2021-02-01,None,1
44,CZ-420619-19-02-0013,2019-02-01,Pravidelná,None,47163,420619,Středočeský kraj,Mělník,Mělník,2019-02-01T17:22:43.4870000+01:00,...,None,None,None,None,None,424849,None,2021-02-01,None,1
45,CZ-420814-19-02-0001,2019-02-01,Pravidelná,None,44405,420814,Středočeský kraj,Lysá nad Labem,Lysá nad Labem,2019-02-01T16:28:52.6800000+01:00,...,None,None,None,None,None,155917,None,2021-02-01,None,1
46,CZ-440326-19-02-0032,2019-02-01,Pravidelná,None,41195,440326,Karlovarský kraj,Karlovy Vary,Jenišov,2019-02-01T16:35:40.1600000+01:00,...,None,None,None,None,None,207945,None,2021-02-01,None,1
47,CZ-420930-19-02-0011,2019-02-01,Pravidelná,None,43281,420930,Středočeský kraj,Říčany,Říčany,2019-02-01T15:53:43.4730000+01:00,...,None,None,None,None,None,137223,None,2021-02-01,None,1
48,CZ-421036-19-02-0013,2019-02-01,Pravidelná,None,40503,421036,Středočeský kraj,Černošice,Roztoky,2019-02-01T16:08:38.7130000+01:00,...,None,None,None,None,None,140389,None,2021-02-01,None,1
49,CZ-521207-19-02-0021,2019-02-01,Pravidelná,None,40937,521207,Středočeský kraj,Rakovník,Nové Strašecí,2019-02-01T18:04:25.5100000+01:00,...,None,None,None,None,None,259050,None,2021-02-01,None,1

                                                        0
CisloProtokolu                        20060291 / 20060291
DatumProhlidky                        20060291 / 20060291
DruhProhlidky                         20060291 / 20060291
RozsahProhlidky                         948272 / 20060291
Prohlidka_OdpovednaOsoba              20060291 / 20060291
Prohlidka_Stanice_Cislo               20060291 / 20060291
Prohlidka_Stanice_Kraj                20060291 / 20060291
Prohlidka_Stanice_ORP                 20060291 / 20060291
Prohlidka_Stanice_Obec                20060291 / 20060291
Prohlidka_Zahajeni                    20060291 / 20060291
Prohlidka_Ukonceni                    20060291 / 20060291
AdministrativniOprava_CisloProtokolu     86900 / 20060291
AdministrativniOprava_DatumProhlidky     86900 / 20060291
Vozidlo_Vin                           20060291 / 20060291
Vozidlo_Druh                          20060291 / 20060291
Vozidlo_Kategorie                     20060291 / 20060291
Vozidlo_Provedeni                      9809875 / 20060291
Vozidlo_Znacka                        20060291 / 20060291
Vozidlo_ObchodniOznaceni              20060291 / 20060291
Vozidlo_TypMotoru                     20043795 / 20060291
Registrace_DatumPrvni                 20049895 / 20060291
Registrace_Stat                       20060290 / 20060291
Registrace_CisloDokladu               19900930 / 20060291
Emise_CisloProtokolu                  20060291 / 20060291
Emise_DatumProhlidky                  20060291 / 20060291
Emise_Stanice_Cislo                   20060291 / 20060291
Emise_Zahajeni                        19886081 / 20060291
Emise_Ukonceni                        19886081 / 20060291
Emise_OdpovednaOsoba                  20060291 / 20060291
Emise_ZakladniPalivo                  20060291 / 20060291
Emise_AlternativniPalivo                456437 / 20060291
Emise_EmisniSystem                    20060291 / 20060291
Emise_VyrobceMotoru                    1825729 / 20060291
Emise_CisloMotoru                      2025230 / 20060291
Technicka_Zahajeni                      948267 / 20060291
Technicka_Ukonceni                      948267 / 20060291
Technicka_OdpovednaOsoba                948272 / 20060291
Adr_Zahajeni                                 0 / 20060291
Adr_Ukonceni                                 0 / 20060291
Adr_OdpovednaOsoba                           0 / 20060291
Adr_Platnost_Periodicka                      0 / 20060291
Adr_Platnost_Meziperiodicka                  0 / 20060291
Adr_KodCisterny                              0 / 20060291
Adr_CisloOsvedceni                           0 / 20060291
Adr_ZavadyText                               0 / 20060291
Adr_Poznamka                                 0 / 20060291
Tsk_OdpovednaOsoba                           0 / 20060291
Vysledek_Odometr                      19977114 / 20060291
Vysledek_Poznamka                       993472 / 20060291
Vysledek_DatumPristiProhlidky         19547736 / 20060291
Vysledek_NalepkaVylepena                948272 / 20060291
Vysledek_Celkovy                      19972973 / 20060291

shape: (1, 52)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Cis ┆ Dat ┆ Dru ┆ Roz ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Adm ┆ Adm ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Reg ┆ Reg ┆ Reg ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Tec ┆ Tec ┆ Tec ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Tsk ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Vys │
│ loP ┆ umP ┆ hPr ┆ sah ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ ini ┆ ini ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ ist ┆ ist ┆ ist ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ hni ┆ hni ┆ hni ┆ _Za ┆ _Uk ┆ _Od ┆ _Pl ┆ _Pl ┆ _Ko ┆ _Ci ┆ _Za ┆ _Po ┆ _Od ┆ led ┆ led ┆ led ┆ led ┆ led │
│ rot ┆ roh ┆ ohl ┆ Pro ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ str ┆ str ┆ o_V ┆ o_D ┆ o_K ┆ o_P ┆ o_Z ┆ o_O ┆ o_T ┆ rac ┆ rac ┆ rac ┆ Cis ┆ Dat ┆ Sta ┆ Zah ┆ Uko ┆ Odp ┆ Zak ┆ Alt ┆ Emi ┆ Vyr ┆ Cis ┆ cka ┆ cka ┆ cka ┆ haj ┆ onc ┆ pov ┆ atn ┆ atn ┆ dCi ┆ slo ┆ vad ┆ zna ┆ pov ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ │
│ oko ┆ lid ┆ idk ┆ hli ┆ _Od ┆ _St ┆ _St ┆ _St ┆ _St ┆ _Za ┆ _Uk ┆ ati ┆ ati ┆ in  ┆ ruh ┆ ate ┆ rov ┆ nac ┆ bch ┆ ypM ┆ e_D ┆ e_S ┆ e_C ┆ loP ┆ umP ┆ nic ┆ aje ┆ nce ┆ ove ┆ lad ┆ ern ┆ sni ┆ obc ┆ loM ┆ _Za ┆ _Uk ┆ _Od ┆ eni ┆ eni ┆ edn ┆ ost ┆ ost ┆ ste ┆ Osv ┆ yTe ┆ mka ┆ edn ┆ Odo ┆ Poz ┆ Dat ┆ Nal ┆ Cel │
│ lu  ┆ ky  ┆ y   ┆ dky ┆ pov ┆ ani ┆ ani ┆ ani ┆ ani ┆ haj ┆ onc ┆ vni ┆ vni ┆ --- ┆ --- ┆ gor ┆ ede ┆ ka  ┆ odn ┆ oto ┆ atu ┆ tat ┆ isl ┆ rot ┆ roh ┆ e_C ┆ ni  ┆ ni  ┆ dna ┆ niP ┆ ati ┆ Sys ┆ eMo ┆ oto ┆ haj ┆ onc ┆ pov ┆ --- ┆ --- ┆ aOs ┆ _Pe ┆ _Me ┆ rny ┆ edc ┆ xt  ┆ --- ┆ aOs ┆ met ┆ nam ┆ umP ┆ epk ┆ kov │
│ --- ┆ --- ┆ --- ┆ --- ┆ edn ┆ ce_ ┆ ce_ ┆ ce_ ┆ ce_ ┆ eni ┆ eni ┆ Opr ┆ Opr ┆ str ┆ str ┆ ie  ┆ ni  ┆ --- ┆ iOz ┆ ru  ┆ mPr ┆ --- ┆ oDo ┆ oko ┆ lid ┆ isl ┆ --- ┆ --- ┆ Oso ┆ ali ┆ vni ┆ tem ┆ tor ┆ ru  ┆ eni ┆ eni ┆ edn ┆ str ┆ str ┆ oba ┆ rio ┆ zip ┆ --- ┆ eni ┆ --- ┆ str ┆ oba ┆ r   ┆ ka  ┆ ris ┆ aVy ┆ y   │
│ str ┆ str ┆ str ┆ str ┆ aOs ┆ Cis ┆ Kra ┆ ORP ┆ Obe ┆ --- ┆ --- ┆ ava ┆ ava ┆     ┆     ┆ --- ┆ --- ┆ str ┆ nac ┆ --- ┆ vni ┆ str ┆ kla ┆ lu  ┆ ky  ┆ o   ┆ str ┆ str ┆ ba  ┆ vo  ┆ Pal ┆ --- ┆ u   ┆ --- ┆ --- ┆ --- ┆ aOs ┆     ┆     ┆ --- ┆ dic ┆ eri ┆ str ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆ tiP ┆ lep ┆ --- │
│     ┆     ┆     ┆     ┆ oba ┆ lo  ┆ j   ┆ --- ┆ c   ┆ str ┆ str ┆ _Ci ┆ _Da ┆     ┆     ┆ str ┆ str ┆     ┆ eni ┆ str ┆ --- ┆     ┆ du  ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ ivo ┆ str ┆ --- ┆ str ┆ str ┆ str ┆ oba ┆     ┆     ┆ str ┆ ka  ┆ odi ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ roh ┆ ena ┆ str │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆     ┆ slo ┆ tum ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆ str ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ cka ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lid ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ Pro ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ky  ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ CZ- ┆ 201 ┆ Pra ┆ nul ┆ 168 ┆ 520 ┆ Stř ┆ Kol ┆ Žab ┆ 201 ┆ 201 ┆ nul ┆ nul ┆ WV1 ┆ NÁK ┆ N1  ┆ nul ┆ VW  ┆ TRA ┆ BPC ┆ 200 ┆ Čes ┆ UB6 ┆ CZ- ┆ 201 ┆ 520 ┆ 201 ┆ 201 ┆ 168 ┆ Naf ┆ nul ┆ Říz ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 309 ┆ nul ┆ 202 ┆ nul ┆ 1   │
│ 520 ┆ 9-0 ┆ vid ┆ l   ┆ 35  ┆ 406 ┆ edo ┆ ín  ┆ ono ┆ 9-0 ┆ 9-0 ┆ l   ┆ l   ┆ ZZZ ┆ LAD ┆     ┆ l   ┆     ┆ NSP ┆     ┆ 7-0 ┆ ká  ┆ 541 ┆ 520 ┆ 9-0 ┆ 406 ┆ 9-0 ┆ 9-0 ┆ 35  ┆ ta  ┆ l   ┆ ený ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 068 ┆ l   ┆ 1-0 ┆ l   ┆     │
│ 406 ┆ 1-0 ┆ eln ┆     ┆     ┆     ┆ čes ┆     ┆ sy  ┆ 1-0 ┆ 1-0 ┆     ┆     ┆ 7HZ ┆ NÍ  ┆     ┆     ┆     ┆ ORT ┆     ┆ 1-0 ┆ rep ┆ 81  ┆ 406 ┆ 1-0 ┆     ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆     ┆     │
│ -19 ┆ 1   ┆ á   ┆     ┆     ┆     ┆ ký  ┆     ┆     ┆ 1T1 ┆ 1T1 ┆     ┆     ┆ 7H0 ┆ AUT ┆     ┆     ┆     ┆ ER  ┆     ┆ 3T0 ┆ ubl ┆     ┆ -19 ┆ 1T1 ┆     ┆ 1T1 ┆ 1T1 ┆     ┆     ┆     ┆ OBD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     │
│ -01 ┆     ┆     ┆     ┆     ┆     ┆ kra ┆     ┆     ┆ 5:2 ┆ 5:4 ┆     ┆     ┆ 794 ┆ OMO ┆     ┆     ┆     ┆     ┆     ┆ 0:0 ┆ ika ┆     ┆ -01 ┆ 5:4 ┆     ┆ 5:2 ┆ 5:3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆ j   ┆     ┆     ┆ 1:4 ┆ 0:0 ┆     ┆     ┆ 25  ┆ BIL ┆     ┆     ┆     ┆     ┆     ┆ 0:0 ┆     ┆     ┆ -00 ┆ 0:0 ┆     ┆ 2:3 ┆ 9:5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9.0 ┆ 5.4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆     ┆     ┆ 01  ┆ 5.4 ┆     ┆ 3.2 ┆ 1.5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 770 ┆ 700 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆ 700 ┆     ┆ 900 ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆ 000 ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +01 ┆ +01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +01 ┆     ┆     ┆     ┆ +01 ┆     ┆ +01 ┆ +01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

Přítomnost sloupců v případě nenastání souběžné technické prohlídky

In [ ]:
describe(df.filter(pl.col('Technicka_OdpovednaOsoba').is_null()))

(948272, 52)

,CisloProtokolu,DatumProhlidky,DruhProhlidky,RozsahProhlidky,Prohlidka_OdpovednaOsoba,Prohlidka_Stanice_Cislo,Prohlidka_Stanice_Kraj,Prohlidka_Stanice_ORP,Prohlidka_Stanice_Obec,Prohlidka_Zahajeni,...,Adr_KodCisterny,Adr_CisloOsvedceni,Adr_ZavadyText,Adr_Poznamka,Tsk_OdpovednaOsoba,Vysledek_Odometr,Vysledek_Poznamka,Vysledek_DatumPristiProhlidky,Vysledek_NalepkaVylepena,Vysledek_Celkovy
0,CZ-3848-19-02-0017,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T10:12:21.8470000+01:00,...,None,None,None,None,None,223122,None,2021-02-01,true,1
1,CZ-3848-19-02-0012,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T08:35:53.7000000+01:00,...,None,None,None,None,None,212424,None,2021-02-01,true,1
2,CZ-3848-19-02-0003,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T07:04:49.5230000+01:00,...,None,None,None,None,None,73587,None,2021-02-01,true,1
3,CZ-3848-19-02-0010,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T08:02:32.0730000+01:00,...,None,None,None,None,None,324927,None,2021-02-01,true,1
4,CZ-3848-19-02-0014,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T09:04:03.5400000+01:00,...,None,None,None,None,None,163604,None,2021-02-01,true,1
5,CZ-3848-19-02-0008,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T07:41:30.9430000+01:00,...,None,None,None,None,None,90820,None,2021-02-01,true,1
6,CZ-3848-19-02-0011,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T08:22:14.2470000+01:00,...,None,None,None,None,None,85407,None,2021-02-01,true,1
7,CZ-3848-19-02-0001,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T06:01:02.5500000+01:00,...,None,None,None,None,None,84630,None,2021-02-01,true,1
8,CZ-3848-19-02-0006,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T07:21:48.2870000+01:00,...,None,None,None,None,None,86289,None,2021-02-01,true,1
9,CZ-3848-19-02-0002,2019-02-01,Pravidelná,Plný,49369,3848,Moravskoslezský kraj,Kopřivnice,Kopřivnice,2019-02-01T06:33:16.4270000+01:00,...,None,None,None,None,None,228053,None,2021-02-01,true,1
10,CZ-3618-21-02-0103,2021-02-01,Pravidelná,Plný,14747,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T15:41:03.3030000+01:00,...,None,None,None,None,None,131150,None,2022-02-01,true,1
11,CZ-3618-21-02-0075,2021-02-01,Pravidelná,Plný,25031,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T12:19:14.7600000+01:00,...,None,None,None,None,None,36430,None,2022-02-01,true,1
12,CZ-3618-21-02-0049,2021-02-01,Pravidelná,Plný,14747,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T10:16:36.9770000+01:00,...,None,None,None,None,None,468296,None,2022-02-01,true,1
13,CZ-3618-21-02-0101,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T15:28:55.7530000+01:00,...,None,None,None,None,None,36354,None,2023-02-01,true,1
14,CZ-3706-21-02-0051,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T15:08:54.0470000+01:00,...,None,None,None,None,None,243198,None,2023-02-01,true,1
15,CZ-3618-21-02-0096,2021-02-01,Pravidelná,Plný,25031,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:54:08.6100000+01:00,...,None,None,None,None,None,13049,None,2022-02-01,true,1
16,CZ-3832-21-02-0030,2021-02-01,Pravidelná,Plný,58659,3832,Moravskoslezský kraj,Karviná,Karviná,2021-02-01T15:51:03.4430000+01:00,...,None,None,None,None,None,77824,None,2023-02-01,true,1
17,CZ-3618-21-02-0099,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T15:13:30.8530000+01:00,...,None,None,None,None,None,166686,None,2023-02-01,true,1
18,CZ-3706-21-02-0050,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T15:02:00.0230000+01:00,...,None,None,None,None,None,51288,None,2023-02-01,true,1
19,CZ-3618-21-02-0094,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:45:55.6100000+01:00,...,None,None,None,None,None,412,None,2023-02-01,true,1
20,CZ-3618-21-02-0095,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:48:48.0100000+01:00,...,None,None,None,None,None,290793,None,2023-02-01,true,1
21,CZ-3618-21-02-0083,2021-02-01,Pravidelná,Plný,14747,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T13:37:23.0600000+01:00,...,None,None,None,None,None,340495,None,2023-02-01,true,1
22,CZ-3618-21-02-0090,2021-02-01,Pred registrací,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:14:50.1600000+01:00,...,None,None,None,None,None,245687,None,2023-02-01,false,1
23,CZ-3618-21-02-0089,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:01:22.0570000+01:00,...,None,None,None,None,None,287335,None,2023-02-01,true,1
24,CZ-3618-21-02-0079,2021-02-01,Pravidelná,Plný,25031,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T13:08:38.6270000+01:00,...,None,None,None,None,None,511473,None,2021-03-03,true,2
25,CZ-3706-21-02-0046,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T14:27:41.2730000+01:00,...,None,None,None,None,None,106231,None,2023-02-01,true,1
26,CZ-3618-21-02-0093,2021-02-01,Pravidelná,Plný,72225,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T14:42:44.8470000+01:00,...,None,None,None,None,None,136941,None,2023-02-01,true,1
27,CZ-3644-21-02-0022,2021-02-01,Pravidelná,Plný,13399,3644,Pardubický kraj,Svitavy,Svitavy,2021-02-01T14:29:55.7470000+01:00,...,None,None,None,None,None,160597,None,2023-02-01,true,1
28,CZ-3840-21-02-0026,2021-02-01,Pravidelná,Plný,34943,3840,Moravskoslezský kraj,Kravaře,Štěpánkovice,2021-02-01T15:09:59.6770000+01:00,...,None,None,None,None,None,167964,None,2021-03-03,true,2
29,CZ-3618-21-02-0088,2021-02-01,Pravidelná,Plný,14747,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T13:56:05.7600000+01:00,...,None,None,None,None,None,759194,None,2022-02-01,true,1
30,CZ-3706-21-02-0048,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T14:50:59.4170000+01:00,...,None,None,None,None,None,412647,None,2023-02-01,true,1
31,CZ-3706-21-02-0045,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T14:23:18.9270000+01:00,...,None,None,None,None,None,70403,None,2023-02-01,true,1
32,CZ-3832-21-02-0028,2021-02-01,Pravidelná,Plný,58659,3832,Moravskoslezský kraj,Karviná,Karviná,2021-02-01T15:00:17.5930000+01:00,...,None,None,None,None,None,123026,None,2023-02-01,true,1
33,CZ-3706-21-02-0043,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T14:17:13.1130000+01:00,...,None,None,None,None,None,49988,None,2023-02-01,true,1
34,CZ-3706-21-02-0044,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T14:22:54.4700000+01:00,...,None,None,None,None,None,84091,None,2023-02-01,true,1
35,CZ-3644-21-02-0021,2021-02-01,Pravidelná,Plný,13399,3644,Pardubický kraj,Svitavy,Svitavy,2021-02-01T14:26:48.5700000+01:00,...,None,None,None,None,None,16267,None,2023-02-01,true,1
36,CZ-3832-21-02-0027,2021-02-01,Pravidelná,Plný,58659,3832,Moravskoslezský kraj,Karviná,Karviná,2021-02-01T14:31:48.6830000+01:00,...,None,None,None,None,None,139429,None,2023-02-01,true,1
37,CZ-3515-21-02-0010,2021-02-01,Pravidelná,Plný,64597,3515,Ústecký kraj,Most,Obrnice,2021-02-01T09:36:07.7530000+01:00,...,None,None,None,None,None,494403,None,2022-02-01,true,1
38,CZ-3515-21-02-0022,2021-02-01,Pravidelná,Plný,64597,3515,Ústecký kraj,Most,Obrnice,2021-02-01T12:25:36.5770000+01:00,...,None,None,None,None,None,679579,None,2022-02-01,true,1
39,CZ-3832-21-02-0023,2021-02-01,Pravidelná,Plný,58659,3832,Moravskoslezský kraj,Karviná,Karviná,2021-02-01T13:50:46.4870000+01:00,...,None,None,None,None,None,94132,None,2021-03-03,true,2
40,CZ-3840-21-02-0023,2021-02-01,Pravidelná,Plný,24075,3840,Moravskoslezský kraj,Kravaře,Štěpánkovice,2021-02-01T14:01:18.2930000+01:00,...,None,None,None,None,None,156903,None,2023-02-01,true,1
41,CZ-3706-21-02-0042,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T13:58:27.3570000+01:00,...,None,None,None,None,None,133363,None,2023-02-01,true,1
42,CZ-3618-21-02-0052,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T10:23:54.4730000+01:00,...,None,None,None,None,None,244445,None,2023-02-01,true,1
43,CZ-3618-21-02-0077,2021-02-01,Pravidelná,Plný,9851,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T12:45:17.2730000+01:00,...,None,None,None,None,None,642109,None,2022-02-01,false,1
44,CZ-3618-21-02-0080,2021-02-01,Pravidelná,Plný,27227,3618,Královéhradecký kraj,Hradec Králové,Hradec Králové,2021-02-01T13:12:08.3030000+01:00,...,None,None,None,None,None,199537,None,2023-02-01,true,1
45,CZ-3515-21-02-0019,2021-02-01,Pravidelná,Plný,64597,3515,Ústecký kraj,Most,Obrnice,2021-02-01T11:37:21.6430000+01:00,...,None,None,None,None,None,409022,None,2022-02-01,true,1
46,CZ-3815-21-02-0063,2021-02-01,Pravidelná,Plný,37,3815,Moravskoslezský kraj,Nový Jičín,Nový Jičín,2021-02-01T12:26:32.0000000+01:00,...,None,None,None,None,None,265176,None,2021-03-03,true,2
47,CZ-3644-21-02-0019,2021-02-01,Pravidelná,Plný,13399,3644,Pardubický kraj,Svitavy,Svitavy,2021-02-01T13:28:27.2570000+01:00,...,None,None,None,None,None,317919,None,2023-02-01,true,1
48,CZ-3706-21-02-0040,2021-02-01,Pred registrací,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T13:32:37.1070000+01:00,...,None,None,None,None,None,244702,None,2023-02-01,false,1
49,CZ-3706-21-02-0039,2021-02-01,Pravidelná,Plný,63603,3706,Kraj Vysočina,Velké Meziříčí,Velké Meziříčí,2021-02-01T13:24:24.5870000+01:00,...,None,None,None,None,None,315550,None,2023-02-01,true,1

                                                    0
CisloProtokolu                        948272 / 948272
DatumProhlidky                        948272 / 948272
DruhProhlidky                         948272 / 948272
RozsahProhlidky                       948272 / 948272
Prohlidka_OdpovednaOsoba              948272 / 948272
Prohlidka_Stanice_Cislo               948272 / 948272
Prohlidka_Stanice_Kraj                948272 / 948272
Prohlidka_Stanice_ORP                 948272 / 948272
Prohlidka_Stanice_Obec                948272 / 948272
Prohlidka_Zahajeni                    948272 / 948272
Prohlidka_Ukonceni                    948272 / 948272
AdministrativniOprava_CisloProtokolu      10 / 948272
AdministrativniOprava_DatumProhlidky      10 / 948272
Vozidlo_Vin                           948272 / 948272
Vozidlo_Druh                          948272 / 948272
Vozidlo_Kategorie                     948272 / 948272
Vozidlo_Provedeni                     501192 / 948272
Vozidlo_Znacka                        948272 / 948272
Vozidlo_ObchodniOznaceni              948272 / 948272
Vozidlo_TypMotoru                     947280 / 948272
Registrace_DatumPrvni                 948207 / 948272
Registrace_Stat                       948272 / 948272
Registrace_CisloDokladu               946559 / 948272
Emise_CisloProtokolu                  948272 / 948272
Emise_DatumProhlidky                  948272 / 948272
Emise_Stanice_Cislo                   948272 / 948272
Emise_Zahajeni                        948270 / 948272
Emise_Ukonceni                        948270 / 948272
Emise_OdpovednaOsoba                  948272 / 948272
Emise_ZakladniPalivo                  948272 / 948272
Emise_AlternativniPalivo               21393 / 948272
Emise_EmisniSystem                    948272 / 948272
Emise_VyrobceMotoru                    29766 / 948272
Emise_CisloMotoru                      15003 / 948272
Technicka_Zahajeni                    948267 / 948272
Technicka_Ukonceni                    948267 / 948272
Technicka_OdpovednaOsoba              948272 / 948272
Adr_Zahajeni                               0 / 948272
Adr_Ukonceni                               0 / 948272
Adr_OdpovednaOsoba                         0 / 948272
Adr_Platnost_Periodicka                    0 / 948272
Adr_Platnost_Meziperiodicka                0 / 948272
Adr_KodCisterny                            0 / 948272
Adr_CisloOsvedceni                         0 / 948272
Adr_ZavadyText                             0 / 948272
Adr_Poznamka                               0 / 948272
Tsk_OdpovednaOsoba                         0 / 948272
Vysledek_Odometr                      944050 / 948272
Vysledek_Poznamka                          0 / 948272
Vysledek_DatumPristiProhlidky         940023 / 948272
Vysledek_NalepkaVylepena              948272 / 948272
Vysledek_Celkovy                      948272 / 948272

shape: (1, 52)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Cis ┆ Dat ┆ Dru ┆ Roz ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Adm ┆ Adm ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Reg ┆ Reg ┆ Reg ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Emi ┆ Tec ┆ Tec ┆ Tec ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Adr ┆ Tsk ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Vys │
│ loP ┆ umP ┆ hPr ┆ sah ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ hli ┆ ini ┆ ini ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ ist ┆ ist ┆ ist ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ se_ ┆ hni ┆ hni ┆ hni ┆ _Za ┆ _Uk ┆ _Od ┆ _Pl ┆ _Pl ┆ _Ko ┆ _Ci ┆ _Za ┆ _Po ┆ _Od ┆ led ┆ led ┆ led ┆ led ┆ led │
│ rot ┆ roh ┆ ohl ┆ Pro ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ dka ┆ str ┆ str ┆ o_V ┆ o_D ┆ o_K ┆ o_P ┆ o_Z ┆ o_O ┆ o_T ┆ rac ┆ rac ┆ rac ┆ Cis ┆ Dat ┆ Sta ┆ Zah ┆ Uko ┆ Odp ┆ Zak ┆ Alt ┆ Emi ┆ Vyr ┆ Cis ┆ cka ┆ cka ┆ cka ┆ haj ┆ onc ┆ pov ┆ atn ┆ atn ┆ dCi ┆ slo ┆ vad ┆ zna ┆ pov ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ │
│ oko ┆ lid ┆ idk ┆ hli ┆ _Od ┆ _St ┆ _St ┆ _St ┆ _St ┆ _Za ┆ _Uk ┆ ati ┆ ati ┆ in  ┆ ruh ┆ ate ┆ rov ┆ nac ┆ bch ┆ ypM ┆ e_D ┆ e_S ┆ e_C ┆ loP ┆ umP ┆ nic ┆ aje ┆ nce ┆ ove ┆ lad ┆ ern ┆ sni ┆ obc ┆ loM ┆ _Za ┆ _Uk ┆ _Od ┆ eni ┆ eni ┆ edn ┆ ost ┆ ost ┆ ste ┆ Osv ┆ yTe ┆ mka ┆ edn ┆ Odo ┆ Poz ┆ Dat ┆ Nal ┆ Cel │
│ lu  ┆ ky  ┆ y   ┆ dky ┆ pov ┆ ani ┆ ani ┆ ani ┆ ani ┆ haj ┆ onc ┆ vni ┆ vni ┆ --- ┆ --- ┆ gor ┆ ede ┆ ka  ┆ odn ┆ oto ┆ atu ┆ tat ┆ isl ┆ rot ┆ roh ┆ e_C ┆ ni  ┆ ni  ┆ dna ┆ niP ┆ ati ┆ Sys ┆ eMo ┆ oto ┆ haj ┆ onc ┆ pov ┆ --- ┆ --- ┆ aOs ┆ _Pe ┆ _Me ┆ rny ┆ edc ┆ xt  ┆ --- ┆ aOs ┆ met ┆ nam ┆ umP ┆ epk ┆ kov │
│ --- ┆ --- ┆ --- ┆ --- ┆ edn ┆ ce_ ┆ ce_ ┆ ce_ ┆ ce_ ┆ eni ┆ eni ┆ Opr ┆ Opr ┆ str ┆ str ┆ ie  ┆ ni  ┆ --- ┆ iOz ┆ ru  ┆ mPr ┆ --- ┆ oDo ┆ oko ┆ lid ┆ isl ┆ --- ┆ --- ┆ Oso ┆ ali ┆ vni ┆ tem ┆ tor ┆ ru  ┆ eni ┆ eni ┆ edn ┆ str ┆ str ┆ oba ┆ rio ┆ zip ┆ --- ┆ eni ┆ --- ┆ str ┆ oba ┆ r   ┆ ka  ┆ ris ┆ aVy ┆ y   │
│ str ┆ str ┆ str ┆ str ┆ aOs ┆ Cis ┆ Kra ┆ ORP ┆ Obe ┆ --- ┆ --- ┆ ava ┆ ava ┆     ┆     ┆ --- ┆ --- ┆ str ┆ nac ┆ --- ┆ vni ┆ str ┆ kla ┆ lu  ┆ ky  ┆ o   ┆ str ┆ str ┆ ba  ┆ vo  ┆ Pal ┆ --- ┆ u   ┆ --- ┆ --- ┆ --- ┆ aOs ┆     ┆     ┆ --- ┆ dic ┆ eri ┆ str ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆ tiP ┆ lep ┆ --- │
│     ┆     ┆     ┆     ┆ oba ┆ lo  ┆ j   ┆ --- ┆ c   ┆ str ┆ str ┆ _Ci ┆ _Da ┆     ┆     ┆ str ┆ str ┆     ┆ eni ┆ str ┆ --- ┆     ┆ du  ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ ivo ┆ str ┆ --- ┆ str ┆ str ┆ str ┆ oba ┆     ┆     ┆ str ┆ ka  ┆ odi ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ roh ┆ ena ┆ str │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆     ┆ slo ┆ tum ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆ str ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ cka ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lid ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ Pro ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ky  ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ CZ- ┆ 201 ┆ Pra ┆ Pln ┆ 493 ┆ 384 ┆ Mor ┆ Kop ┆ Kop ┆ 201 ┆ 201 ┆ nul ┆ nul ┆ VF7 ┆ OSO ┆ M1  ┆ nul ┆ CIT ┆ C2  ┆ NFS ┆ 200 ┆ Čes ┆ UG  ┆ CZ- ┆ 201 ┆ 384 ┆ 201 ┆ 201 ┆ 693 ┆ Ben ┆ nul ┆ Říz ┆ nul ┆ nul ┆ 201 ┆ 201 ┆ 693 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 223 ┆ nul ┆ 202 ┆ tru ┆ 1   │
│ 384 ┆ 9-0 ┆ vid ┆ ý   ┆ 69  ┆ 8   ┆ avs ┆ řiv ┆ řiv ┆ 9-0 ┆ 9-0 ┆ l   ┆ l   ┆ JMN ┆ BNÍ ┆     ┆ l   ┆ ROË ┆     ┆     ┆ 5-0 ┆ ká  ┆ 217 ┆ 003 ┆ 9-0 ┆ 8   ┆ 9-0 ┆ 9-0 ┆     ┆ zín ┆ l   ┆ ený ┆ l   ┆ l   ┆ 9-0 ┆ 9-0 ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 122 ┆ l   ┆ 1-0 ┆ e   ┆     │
│ 8-1 ┆ 2-0 ┆ eln ┆     ┆     ┆     ┆ kos ┆ nic ┆ nic ┆ 2-0 ┆ 2-0 ┆     ┆     ┆ FSC ┆ AUT ┆     ┆     ┆ N   ┆     ┆     ┆ 1-2 ┆ rep ┆ 468 ┆ 848 ┆ 2-0 ┆     ┆ 2-0 ┆ 2-0 ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ 2-0 ┆ 2-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆     │
│ 9-0 ┆ 1   ┆ á   ┆     ┆     ┆     ┆ lez ┆ e   ┆ e   ┆ 1T1 ┆ 1T1 ┆     ┆     ┆ 971 ┆ OMO ┆     ┆     ┆     ┆     ┆     ┆ 7T0 ┆ ubl ┆     ┆ -19 ┆ 1T1 ┆     ┆ 1T1 ┆ 1T1 ┆     ┆     ┆     ┆ OBD ┆     ┆     ┆ 1T1 ┆ 1T1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     │
│ 2-0 ┆     ┆     ┆     ┆     ┆     ┆ ský ┆     ┆     ┆ 0:1 ┆ 1:2 ┆     ┆     ┆ 657 ┆ BIL ┆     ┆     ┆     ┆     ┆     ┆ 0:0 ┆ ika ┆     ┆ -02 ┆ 1:2 ┆     ┆ 0:1 ┆ 0:1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0:5 ┆ 1:2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 017 ┆     ┆     ┆     ┆     ┆     ┆ kra ┆     ┆     ┆ 2:2 ┆ 3:3 ┆     ┆     ┆ 91  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0:0 ┆     ┆     ┆ -00 ┆ 3:3 ┆     ┆ 4:1 ┆ 9:5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1:3 ┆ 2:3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ j   ┆     ┆     ┆ 1.8 ┆ 1.2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆     ┆     ┆ 17  ┆ 1.2 ┆     ┆ 4.4 ┆ 7.5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4.0 ┆ 0.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 470 ┆ 300 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆ 300 ┆     ┆ 900 ┆ 630 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆ 000 ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +01 ┆ +01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +01 ┆     ┆     ┆     ┆ +01 ┆     ┆ +01 ┆ +01 ┆     ┆     ┆     ┆     ┆     ┆     ┆ +01 ┆ +01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

### Odstranění prázdných sloupců

In [5]:
adr_cols = [col for col in df.columns if 'Adr' in col]
df = df.drop(adr_cols + ['Tsk_OdpovednaOsoba'])

### Převedení sloupců týkajících se technické prohlídky na indikátor přítomnosti z důvodu řídkého výskytu

In [6]:
technicka_cols = ['RozsahProhlidky', 'Technicka_Zahajeni', 'Technicka_Ukonceni', 'Technicka_OdpovednaOsoba', 'Vysledek_NalepkaVylepena']
df = df.with_columns(pl.any_horizontal(pl.col(technicka_cols).is_not_null()).alias('Technicka_Pritomo')).drop(technicka_cols)
short_display(df)
display_counts(df)

(19748587, 38)

,CisloProtokolu,DatumProhlidky,DruhProhlidky,Prohlidka_OdpovednaOsoba,Prohlidka_Stanice_Cislo,Prohlidka_Stanice_Kraj,Prohlidka_Stanice_ORP,Prohlidka_Stanice_Obec,Prohlidka_Zahajeni,Prohlidka_Ukonceni,...,Emise_ZakladniPalivo,Emise_AlternativniPalivo,Emise_EmisniSystem,Emise_VyrobceMotoru,Emise_CisloMotoru,Vysledek_Odometr,Vysledek_Poznamka,Vysledek_DatumPristiProhlidky,Vysledek_Celkovy,Technicka_Pritomo
0,CZ-520406-19-01-0001,2019-01-01,Pravidelná,16835,520406,Středočeský kraj,Kolín,Žabonosy,2019-01-01T15:21:49.0770000+01:00,2019-01-01T15:40:05.4700000+01:00,...,Nafta,None,Řízený s OBD,None,None,309068,None,2021-01-01,1,False
1,CZ-420930-19-01-0001,2019-01-01,Pravidelná,43281,420930,Středočeský kraj,Říčany,Říčany,2019-01-01T14:35:04.4400000+01:00,2019-01-01T15:06:17.8430000+01:00,...,Nafta,None,Řízený bez OBD,None,None,169952,None,2021-01-01,1,False
2,CZ-480811-23-01-0001,2023-01-01,Pravidelná,36479,480811,Olomoucký kraj,Přerov,Kojetín,2023-01-01T12:21:49.8570000+01:00,2023-01-01T12:36:59.8530000+01:00,...,Nafta,None,Řízený s OBD,None,None,241379,None,2025-01-01,1,False
3,CZ-420221-23-01-0004,2023-01-01,Pravidelná,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T17:25:41.6570000+01:00,2023-01-01T17:42:24.7630000+01:00,...,Nafta,None,Řízený s OBD,None,-,65923,None,2025-01-01,1,False
4,CZ-420221-23-01-0001,2023-01-01,Pravidelná,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:05:05.4600000+01:00,2023-01-01T16:20:09.7700000+01:00,...,Nafta,None,Řízený s OBD,None,-,264005,None,2025-01-01,1,False
5,CZ-420221-23-01-0003,2023-01-01,Pravidelná,44365,420221,Středočeský kraj,Beroun,Bavoryně,2023-01-01T16:56:47.6530000+01:00,2023-01-01T17:07:00.6770000+01:00,...,Nafta,None,Řízený s OBD,None,-,146446,None,2025-01-01,1,False
6,CZ-170901-23-01-0001,2023-01-01,Pravidelná,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:23:52.2530000+01:00,2023-01-01T19:36:57.2500000+01:00,...,Nafta,None,Řízený s OBD,None,None,237886,None,2025-01-01,1,False
7,CZ-170901-23-01-0002,2023-01-01,Pravidelná,89493,170901,Olomoucký kraj,Prostějov,Bedihošť,2023-01-01T19:40:36.1970000+01:00,2023-01-01T19:53:31.8530000+01:00,...,Nafta,None,Řízený s OBD,None,None,210028,None,2025-01-01,1,False
8,CZ-520406-24-01-0001,2024-01-01,Pravidelná,1308,520406,Středočeský kraj,Kolín,Žabonosy,2024-01-01T11:30:09.4530000+01:00,2024-01-01T11:49:50.8200000+01:00,...,Benzín,None,Řízený s OBD,None,None,237115,None,2026-01-01,1,False
9,CZ-480811-24-01-0001,2024-01-01,Pravidelná,36479,480811,Olomoucký kraj,Přerov,Kojetín,2024-01-01T16:21:48.9530000+01:00,2024-01-01T16:36:21.9500000+01:00,...,Nafta,None,Řízený s OBD,None,None,263886,None,2026-01-01,1,False

                                             0
CisloProtokolu                        19748587
DatumProhlidky                        19748587
DruhProhlidky                         19748587
Prohlidka_OdpovednaOsoba              19748587
Prohlidka_Stanice_Cislo               19748587
Prohlidka_Stanice_Kraj                19748587
Prohlidka_Stanice_ORP                 19748587
Prohlidka_Stanice_Obec                19748587
Prohlidka_Zahajeni                    19748587
Prohlidka_Ukonceni                    19748587
AdministrativniOprava_CisloProtokolu     86147
AdministrativniOprava_DatumProhlidky     86147
Vozidlo_Vin                           19748587
Vozidlo_Druh                          19748587
Vozidlo_Kategorie                     19748587
Vozidlo_Provedeni                      9690917
Vozidlo_Znacka                        19748587
Vozidlo_ObchodniOznaceni              19748587
Vozidlo_TypMotoru                     19732203
Registrace_DatumPrvni                 19738240
Registrace_Stat                       19748586
Registrace_CisloDokladu               19590253
Emise_CisloProtokolu                  19748587
Emise_DatumProhlidky                  19748587
Emise_Stanice_Cislo                   19748587
Emise_Zahajeni                        19575311
Emise_Ukonceni                        19575311
Emise_OdpovednaOsoba                  19748587
Emise_ZakladniPalivo                  19748587
Emise_AlternativniPalivo                449533
Emise_EmisniSystem                    19748587
Emise_VyrobceMotoru                    1819343
Emise_CisloMotoru                      2009654
Vysledek_Odometr                      19666001
Vysledek_Poznamka                       967244
Vysledek_DatumPristiProhlidky         19245338
Vysledek_Celkovy                      19661450
Technicka_Pritomo                     19748587

# Podmínka pro osobní dieselová vozidla
## Analýza relevantních sloupců

In [7]:
df.filter(pl.col('Vozidlo_Druh') == 'OSOBNÍ AUTOMOBIL')['Vozidlo_Kategorie'].value_counts()

shape: (6, 2)
┌───────────────────┬──────────┐
│ Vozidlo_Kategorie ┆ count    │
│ ---               ┆ ---      │
│ str               ┆ u32      │
╞═══════════════════╪══════════╡
│ M1                ┆ 16044202 │
│ M1G               ┆ 483923   │
│ LA                ┆ 1        │
│ M2                ┆ 1        │
│ N1                ┆ 48       │
│ N3                ┆ 1        │
└───────────────────┴──────────┘

In [8]:
df['Emise_ZakladniPalivo'].value_counts()

shape: (6, 2)
┌──────────────────────┬──────────┐
│ Emise_ZakladniPalivo ┆ count    │
│ ---                  ┆ ---      │
│ str                  ┆ u32      │
╞══════════════════════╪══════════╡
│ Směs                 ┆ 36231    │
│ LNG                  ┆ 399      │
│ CNG                  ┆ 64512    │
│ Benzín               ┆ 9269023  │
│ Nafta                ┆ 10378161 │
│ LPG                  ┆ 261      │
└──────────────────────┴──────────┘

In [9]:
df['Emise_AlternativniPalivo'].value_counts()

shape: (4, 2)
┌──────────────────────────┬──────────┐
│ Emise_AlternativniPalivo ┆ count    │
│ ---                      ┆ ---      │
│ str                      ┆ u32      │
╞══════════════════════════╪══════════╡
│ null                     ┆ 19299054 │
│ LPG                      ┆ 416837   │
│ LNG                      ┆ 144      │
│ CNG                      ┆ 32552    │
└──────────────────────────┴──────────┘

## Filtrace na základě daných sloupců

In [10]:
df_diesel = df.filter((pl.col('Vozidlo_Druh') == 'OSOBNÍ AUTOMOBIL') & (pl.col('Emise_ZakladniPalivo') == 'Nafta') & pl.col('Emise_AlternativniPalivo').is_null())

### Selekce relevantního sloupce pro filtraci

In [13]:
short_display(df_diesel[['CisloProtokolu', 'Emise_CisloProtokolu']].filter(pl.col('CisloProtokolu') != pl.col('Emise_CisloProtokolu')))

(337376, 2)

       CisloProtokolu  Emise_CisloProtokolu
0  CZ-3848-19-02-0012  CZ-003848-19-02-0012
1  CZ-3848-19-02-0010  CZ-003848-19-02-0010
2  CZ-3848-19-02-0006  CZ-003848-19-02-0006
3  CZ-3848-19-02-0002  CZ-003848-19-02-0002
4  CZ-3618-21-02-0090  CZ-003618-21-02-0090
5  CZ-3618-21-02-0089  CZ-003618-21-02-0089
6  CZ-3706-21-02-0046  CZ-003706-21-02-0046
7  CZ-3644-21-02-0022  CZ-003644-21-02-0022
8  CZ-3706-21-02-0048  CZ-003706-21-02-0048
9  CZ-3840-21-02-0023  CZ-003840-21-02-0023

Pouze v jednom případě se čísla protokolu u emise a prohlídky liší. V datasetu dat z měření se vyskytuje Emise_CisloProtokolu. (Zajmavé je, že zrovna daný záznam je duplicitní, což indikuje, že by se mohlo jednat o chybu.)

In [30]:
short_display(df_diesel[['CisloProtokolu', 'Emise_CisloProtokolu']].filter(pl.col('CisloProtokolu') != pl.col('Emise_CisloProtokolu').str.replace(r'^CZ-(0+)(\d+)', r'CZ-${2}')))

(1, 2)

       CisloProtokolu  Emise_CisloProtokolu
0  CZ-3420-24-02-0512  CZ-540308-24-02-0512

Téměř všechny záznamy z datasetu dat z měřících přístrojů mají ekvivalentní záznam v datasetu prohlídek - dává tedy smysl použít sloupce z datasetu prohlídek pro filtrace osobních dieselových vozidel.

In [ ]:
# cislo_protokolu_technicka = set(df_technicka.select(pl.col('Emise_CisloProtokolu').str.replace(r'^CZ-(0+)(\d+)', r'CZ-${2}'))['Emise_CisloProtokolu'])
# cislo_protokolu_mereni = set(df_all.select(pl.col('CisloProtokolu').str.replace(r'^CZ-(0+)(\d+)', r'CZ-${2}'))['CisloProtokolu'])
# cislo_protokolu_mereni - cislo_protokolu_technicka

# RESULT:
# {'CZ-120902-20-07-0174', 'CZ-410432-20-08-0152'}