In [1]:
import os
import time
import random
import warnings

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from lxml import etree # type: ignore <- pylance milně hlásí chybu
from pathlib import Path
import time
import sys
import polars as pl
import polars.selectors as cs
import json
import pickle
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from ydata_profiling import ProfileReport

from utils import *
from schemas import *
from processing import *

pl.Config.set_tbl_cols(-1)
os.chdir(r'E:\CVUT_BAP')
SEED=42

# Načtení datasetu se stanicemi

In [15]:
df = pl.read_parquet('kod/data/stanice_stk_a_sme/parquet/stanice', schema=stanice_schema)
describe(df)

(1409, 26)

,Stanice_Cislo,Stanice_Adresa_Kraj,Stanice_Adresa_Okres,Stanice_Adresa_Orp,Stanice_Adresa_Obec,Stanice_Adresa_Ulice,Stanice_Adresa_Psc,Stanice_Kontakt_Telefon,Stanice_Kontakt_Email,Provozovatel_Ico,...,Stk_Pritomno,Stk_Osvedceni_Kategorie,Adr_Pritomno,Adr_Osvedceni_Kategorie,SmeZkusebni_Pritomno,SmeZkusebni_Osvedceni_Kategorie,Sme_Pritomno,Sme_Osvedceni_Kategorie,Sme_Osvedceni_EmisniSystem,Sme_Osvedceni_Palivo
0,110301,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Koněvova 411/143,13000,704372631,emitech@email.cz,17389631,...,False,NaN,False,NaN,False,NaN,True,4.0,2.0,2.0
1,110302,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Osiková 2688/2,13000,605339922,stk3130@seznam.cz,7100639,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
2,110401,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Lipenská 616,14900,608238686,m.o.t.service@centrum.cz,71715177,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
3,110501,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Bavorská 2666/16,15500,+420 271 077 890,ota.kolmann@daimlertruck.com,6418147,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,3.0
4,110502,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Jeremiášova 947/16,15500,774264790,autosprint.stodulky@gmail.com,11716541,...,False,NaN,False,NaN,False,NaN,True,7.0,2.0,3.0
5,110503,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Plzeňská 305/215e,15000,257216489,sen.k.trojan@seznam.cz,17145279,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
6,110601,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Reinerova 811/5,16300,608910916,recepce@papousek.cz,48028321,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,2.0
7,110801,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Bešťákova 567/3,18200,722003300,stk@stkpraha8.cz,24847224,...,False,NaN,False,NaN,False,NaN,True,7.0,2.0,4.0
8,110802,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,K Ládví 925,18000,604288244,autoholub@email.cz,62421247,...,False,NaN,False,NaN,False,NaN,True,7.0,2.0,4.0
9,110901,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,"Kostelecká ul., parc.č.756/48,756/49,756/50,15788",19000,777277177,stk31.31@seznam.cz,7100639,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
10,110903,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Nad rybníkem 4,19012,777307370,petr.bacak@seznam.cz,47103914,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,2.0
11,110904,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Chlumecká 765/6,19819,720696972,info.stkcernymost@gmail.com,25065335,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
12,110905,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Stupská 9,19000,774702230,albanetosro@gmail.com,6597629,...,False,NaN,False,NaN,False,NaN,True,4.0,2.0,2.0
13,110906,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Podnikatelská I č.p. 652,19011,222560688,stkpraha@stkpraha.cz,61063606,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,5.0
14,111001,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Kutnohorská 312,10900,606864133,jan.melmer3@gmail.com,76512584,...,False,NaN,False,NaN,False,NaN,True,NaN,2.0,2.0
15,111002,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Brigádníků 3067/6,10000,+420721316915,info@stkstrasnice.cz,61680214,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,4.0
16,111003,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,K Hrušovu 292/4,10200,+420-721556020,strnad@autobase.cz,9154701,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,2.0
17,111114,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,TISOfline,10000,72591112,peter.burik@cfz.cz,63991551,...,False,NaN,False,NaN,False,NaN,True,NaN,NaN,NaN
18,111115,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Odbytová,11000,602219789,jiri.tronicek@cz.bosch.com,11111222,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
19,111116,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Odbytová,11000,+421911188594,tomas.rosival@toptest.sk,11111222,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
20,111117,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Odbytová,11000,+421905738720,jan.mika@ttc.sk,11111222,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
21,111118,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Odbytová,11000,602219789,jiri.tronicek@cz.bosch.com,11111222,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
22,111122,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,nábřeží Ludvíka Svobody 1222/12,11000,1,CSPSD,66003008,...,False,NaN,False,NaN,False,NaN,True,NaN,2.0,5.0
23,111133,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Türkova 1001,11000,3,DEKRA,66003008,...,False,NaN,False,NaN,False,NaN,True,NaN,2.0,5.0
24,111134,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Přerovská,74545,12345678,email@cz,49240188,...,False,NaN,False,NaN,False,NaN,True,NaN,NaN,NaN
25,111135,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Novodvorská 994,14221,602188381,Pavel.Sterba@tuvsud.com,63987121,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
26,111144,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Českomoravská,11000,3,TÜV,66003008,...,False,NaN,False,NaN,False,NaN,True,NaN,2.0,5.0
27,111155,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,"Náměstí Padlých 20, Nebušice",16400,734 717 143,norbert.grosser@stkcz.cz,24828866,...,False,NaN,False,NaN,False,NaN,True,NaN,NaN,NaN
28,111156,Olomoucký kraj,Přerov,Přerov,Přerov,9. května 90/b,75002,777808680,kanovsky@motoexpert.cz,24828866,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
29,120101,Středočeský kraj,Benešov,Votice,Olbramovice,Olbramovice,25901,739343434,emise@davocar.cz,27934799,...,False,NaN,False,NaN,False,NaN,True,4.0,2.0,2.0
30,120201,Středočeský kraj,Beroun,Hořovice,Hořovice,Masarykova 161,26801,777730281,kancelar@ekotech-hr.cz,27630668,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,5.0
31,120301,Středočeský kraj,Kladno,Kladno,Kladno,28. října 1503,27309,603203106,info@stk-kladno.cz,27389481,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,5.0
32,120401,Středočeský kraj,Kolín,Kolín,Nebovidy,Nebovidy 157,28002,777802488,autobazar@clevercars.cz,27959651,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,3.0
33,120402,Středočeský kraj,Kolín,Kolín,Zásmuky,Na Pile 611,28144,602317498,info@stkzasmuky.cz,2228459,...,False,NaN,False,NaN,False,NaN,True,4.0,2.0,5.0
34,120403,Středočeský kraj,Kolín,Český Brod,Tuklaty,Hlavní 250,25082,+420725715815,hajek@autocentrumhajek.cz,24269239,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,4.0
35,120404,Středočeský kraj,Kolín,Kolín,Kolín,Zengrova 131,28002,777995182,coubalv@seznam.cz,7785950,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,3.0
36,120501,Středočeský kraj,Kutná Hora,Kutná Hora,Suchdol,Dobřeň 26,28401,776852928,info@automasin.cz,10242601,...,False,NaN,False,NaN,False,NaN,True,6.0,2.0,2.0
37,120502,Středočeský kraj,Kutná Hora,Kutná Hora,Kutná Hora,Hrnčířská 214,28401,606814843,hurych@unikom.cz,46355821,...,False,NaN,False,NaN,False,NaN,True,5.0,2.0,2.0
38,120901,Středočeský kraj,Praha-východ,Říčany,Struhařov,V Zahradách 181,25164,777088580,petrkajuk@seznam.cz,13261801,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,2.0
39,120903,Středočeský kraj,Praha-východ,Brandýs nad Labem-Stará Boleslav,Brandýs nad Labem-Stará Boleslav,Karla Lípy 1678,25001,733 110 430,info@cfz.cz,7100728,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
40,130101,Jihočeský kraj,České Budějovice,České Budějovice,České Budějovice,Vrbenská 1070/10,37006,776756050,emisecb@email.cz,7626720,...,False,NaN,False,NaN,False,NaN,True,5.0,2.0,4.0
41,130102,Jihočeský kraj,České Budějovice,České Budějovice,České Budějovice,Okružní 665,37001,770198037,emise@passcb.cz,28100131,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,2.0
42,130401,Vysočina,Pelhřimov,Pelhřimov,Pelhřimov,Krasíkovická 1787,39301,732 298 733,sme130401@seznam.cz,21837775,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
43,130601,Jihočeský kraj,Prachatice,Vimperk,Vacov,Vlkonice 147,38486,723816475,martin.ctvrtnik@tiscali.cz,72166363,...,False,NaN,False,NaN,False,NaN,True,6.0,2.0,2.0
44,130602,Jihočeský kraj,Prachatice,Prachatice,Těšovice,Těšovice 60,38301,775297163,jan.pinter@kutaservis.cz,11825952,...,False,NaN,False,NaN,False,NaN,True,8.0,2.0,2.0
45,130701,Jihočeský kraj,Strakonice,Vodňany,Vodňany,Stožická 840,389 01,383382522,stk@stkvodnany.cz,25152211,...,False,NaN,False,NaN,False,NaN,True,9.0,2.0,5.0
46,130801,Jihočeský kraj,Tábor,Tábor,Bechyně,Bežerovice 52,39165,602837333,autabechyne@seznam.cz,45004871,...,False,NaN,False,NaN,False,NaN,True,8.0,2.0,3.0
47,130802,Jihočeský kraj,Tábor,Tábor,Opařany,Opařany 312,39161,724375455,servis@kaftransport.cz,25150812,...,False,NaN,False,NaN,False,NaN,True,8.0,2.0,2.0
48,140301,Karlovarský kraj,Karlovy Vary,Karlovy Vary,Karlovy Vary,Hory 286,36001,+420602506251,autodiselservis@seznam.cz,23980508,...,False,NaN,False,NaN,False,NaN,True,7.0,2.0,2.0
49,140401,Plzeňský kraj,Klatovy,Klatovy,Klatovy,Chlistov 73,33901,+420 723 439 518,dovozvozideljh@seznam.cz,73674443,...,False,NaN,False,NaN,False,NaN,True,2.0,2.0,2.0

                                           0
Stanice_Cislo                    1409 / 1409
Stanice_Adresa_Kraj              1409 / 1409
Stanice_Adresa_Okres             1409 / 1409
Stanice_Adresa_Orp               1409 / 1409
Stanice_Adresa_Obec              1409 / 1409
Stanice_Adresa_Ulice             1409 / 1409
Stanice_Adresa_Psc               1409 / 1409
Stanice_Kontakt_Telefon          1409 / 1409
Stanice_Kontakt_Email            1409 / 1409
Provozovatel_Ico                 1409 / 1409
Provozovatel_Nazev               1409 / 1409
Provozovatel_Adresa_Obec         1409 / 1409
Provozovatel_Adresa_Ulice        1409 / 1409
Provozovatel_Adresa_Psc          1409 / 1409
Provozovatel_Kontakt_Telefon     1208 / 1409
Provozovatel_Kontakt_Email       1362 / 1409
Stk_Pritomno                     1409 / 1409
Stk_Osvedceni_Kategorie           228 / 1409
Adr_Pritomno                     1409 / 1409
Adr_Osvedceni_Kategorie            17 / 1409
SmeZkusebni_Pritomno             1409 / 1409
SmeZkusebni_Osvedceni_Kategorie   198 / 1409
Sme_Pritomno                     1409 / 1409
Sme_Osvedceni_Kategorie           456 / 1409
Sme_Osvedceni_EmisniSystem       1388 / 1409
Sme_Osvedceni_Palivo             1388 / 1409

shape: (1, 26)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Stk ┆ Stk ┆ Adr ┆ Adr ┆ Sme ┆ Sme ┆ Sme ┆ Sme ┆ Sme ┆ Sme │
│ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ voz ┆ voz ┆ voz ┆ voz ┆ voz ┆ voz ┆ voz ┆ _Pr ┆ _Os ┆ _Pr ┆ _Os ┆ Zku ┆ Zku ┆ _Pr ┆ _Os ┆ _Os ┆ _Os │
│ e_C ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ e_K ┆ e_K ┆ ova ┆ ova ┆ ova ┆ ova ┆ ova ┆ ova ┆ ova ┆ ito ┆ ved ┆ ito ┆ ved ┆ seb ┆ seb ┆ ito ┆ ved ┆ ved ┆ ved │
│ isl ┆ dre ┆ dre ┆ dre ┆ dre ┆ dre ┆ dre ┆ ont ┆ ont ┆ tel ┆ tel ┆ tel ┆ tel ┆ tel ┆ tel ┆ tel ┆ mno ┆ cen ┆ mno ┆ cen ┆ ni_ ┆ ni_ ┆ mno ┆ cen ┆ cen ┆ cen │
│ o   ┆ sa_ ┆ sa_ ┆ sa_ ┆ sa_ ┆ sa_ ┆ sa_ ┆ akt ┆ akt ┆ _Ic ┆ _Na ┆ _Ad ┆ _Ad ┆ _Ad ┆ _Ko ┆ _Ko ┆ --- ┆ i_K ┆ --- ┆ i_K ┆ Pri ┆ Osv ┆ --- ┆ i_K ┆ i_E ┆ i_P │
│ --- ┆ Kra ┆ Okr ┆ Orp ┆ Obe ┆ Uli ┆ Psc ┆ _Te ┆ _Em ┆ o   ┆ zev ┆ res ┆ res ┆ res ┆ nta ┆ nta ┆ str ┆ ate ┆ str ┆ ate ┆ tom ┆ edc ┆ str ┆ ate ┆ mis ┆ ali │
│ str ┆ j   ┆ es  ┆ --- ┆ c   ┆ ce  ┆ --- ┆ lef ┆ ail ┆ --- ┆ --- ┆ a_O ┆ a_U ┆ a_P ┆ kt_ ┆ kt_ ┆     ┆ gor ┆     ┆ gor ┆ no  ┆ eni ┆     ┆ gor ┆ niS ┆ vo  │
│     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆ on  ┆ --- ┆ str ┆ str ┆ bec ┆ lic ┆ sc  ┆ Tel ┆ Ema ┆     ┆ ie  ┆     ┆ ie  ┆ --- ┆ _Ka ┆     ┆ ie  ┆ yst ┆ --- │
│     ┆ str ┆ str ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ e   ┆ --- ┆ efo ┆ il  ┆     ┆ --- ┆     ┆ --- ┆ str ┆ teg ┆     ┆ --- ┆ em  ┆ lis │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ n   ┆ --- ┆     ┆ lis ┆     ┆ lis ┆     ┆ ori ┆     ┆ lis ┆ --- ┆ t[s │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆ t[s ┆     ┆ t[s ┆     ┆ …   ┆     ┆ t[s ┆ lis ┆ tr] │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ tr] ┆     ┆ tr] ┆     ┆ --- ┆     ┆ tr] ┆ t[s ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lis ┆     ┆     ┆ tr] ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 110 ┆ Hla ┆ Hla ┆ Hla ┆ Pra ┆ Kon ┆ 130 ┆ 704 ┆ emi ┆ 173 ┆ Emi ┆ Pra ┆ Cho ┆ 141 ┆ 704 ┆ emi ┆ Fal ┆ nul ┆ Fal ┆ nul ┆ Fal ┆ nul ┆ Tru ┆ ["M ┆ ["N ┆ ["B │
│ 301 ┆ vní ┆ vní ┆ vní ┆ ha  ┆ ěvo ┆ 00  ┆ 372 ┆ tec ┆ 896 ┆ tec ┆ ha  ┆ cer ┆ 00  ┆ 372 ┆ tec ┆ se  ┆ l   ┆ se  ┆ l   ┆ se  ┆ l   ┆ e   ┆ 1", ┆ ERI ┆ A", │
│     ┆ měs ┆ měs ┆ měs ┆     ┆ va  ┆     ┆ 631 ┆ h@e ┆ 31  ┆ h   ┆     ┆ ads ┆     ┆ 000 ┆ h@e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "M2 ┆ ZEN ┆ "NM │
│     ┆ to  ┆ to  ┆ to  ┆     ┆ 411 ┆     ┆     ┆ mai ┆     ┆ s.r ┆     ┆ ká  ┆     ┆     ┆ mai ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ Y", ┆ "]  │
│     ┆ Pra ┆ Pra ┆ Pra ┆     ┆ /14 ┆     ┆     ┆ l.c ┆     ┆ .o. ┆     ┆ 304 ┆     ┆     ┆ l.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ "RI ┆     │
│     ┆ ha  ┆ ha  ┆ ha  ┆     ┆ 3   ┆     ┆     ┆ z   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "N2 ┆ ZEN ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "]  ┆ Y"] ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [17]:
df = transform_stanice(cast_stanice(df))
describe(df)

(1409, 16)

,Stanice_Cislo,Stanice_Adresa_Kraj,Stanice_Adresa_Okres,Stanice_Adresa_Orp,Stanice_Adresa_Obec,Provozovatel_Nazev,Provozovatel_Adresa_Obec,Provozovatel_Kontakt_Telefon,Provozovatel_Kontakt_Email,Stk_Pritomno,Adr_Pritomno,SmeZkusebni_Pritomno,Sme_Pritomno,Sme_Osvedceni_Kategorie,Sme_Osvedceni_EmisniSystem,Sme_Osvedceni_Palivo
0,110301,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Emitech s.r.o.,Praha,True,True,False,False,False,True,4.0,2.0,2.0
1,110302,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,E2F2 s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,4.0
2,110401,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Tomáš Krejčí,Praha,True,True,False,False,False,True,2.0,2.0,4.0
3,110501,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Daimler Truck Česká republika s.r.o.,Praha,True,True,False,False,False,True,9.0,2.0,3.0
4,110502,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Autosprint Stodůlky s.r.o.,Praha,False,True,False,False,False,True,7.0,2.0,3.0
5,110503,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,AUTOTEST-EMISE MOTOL s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,4.0
6,110601,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,AUTO PAPOUŠEK s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,2.0
7,110801,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,CZ MARTIN Oil s.r.o.,Praha,False,True,False,False,False,True,7.0,2.0,4.0
8,110802,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Jan Holub,Praha,True,True,False,False,False,True,7.0,2.0,4.0
9,110901,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,E2F2 s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,4.0
10,110903,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Petr Bačák,Praha,True,True,False,False,False,True,2.0,2.0,2.0
11,110904,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,"Antonín Indra STK,spol. s r.o.",Praha,True,True,False,False,False,True,2.0,2.0,4.0
12,110905,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,ALBANETO s.r.o.,Praha,True,True,False,False,False,True,4.0,2.0,2.0
13,110906,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,PRONTO STK s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,5.0
14,111001,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Jan Melmer,Praha,False,True,False,False,False,True,NaN,2.0,2.0
15,111002,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,AUTORECAR s.r.o.,Divišov,False,True,False,False,False,True,2.0,2.0,4.0
16,111003,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,AUTO BASE s.r.o.,Praha,True,True,False,False,False,True,2.0,2.0,2.0
17,111114,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,BĚLOHRADSKÝ spol. s r.o.,Praha,True,True,False,False,False,True,NaN,NaN,NaN
18,111115,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Robert BOSCH,Praha,True,True,False,False,False,True,9.0,2.0,5.0
19,111116,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Robert BOSCH,Praha,True,True,False,False,False,True,9.0,2.0,5.0
20,111117,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Robert BOSCH,Praha,True,True,False,False,False,True,9.0,2.0,5.0
21,111118,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Robert BOSCH,Praha,True,True,False,False,False,True,9.0,2.0,5.0
22,111122,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Ministerstvo dopravy,Praha,True,True,False,False,False,True,NaN,2.0,5.0
23,111133,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Ministerstvo dopravy,Praha,True,True,False,False,False,True,NaN,2.0,5.0
24,111134,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,DEKRA CZ a.s.,Praha,True,True,False,False,False,True,NaN,NaN,NaN
25,111135,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,TÜV SÜD Czech s.r.o.,Praha,True,True,False,False,False,True,9.0,2.0,5.0
26,111144,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,Ministerstvo dopravy,Praha,True,True,False,False,False,True,NaN,2.0,5.0
27,111155,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,STK CZ s.r.o.,Praha,False,True,False,False,False,True,NaN,NaN,NaN
28,111156,Olomoucký kraj,Přerov,Přerov,Přerov,STK CZ s.r.o.,Praha,False,True,False,False,False,True,9.0,2.0,5.0
29,120101,Středočeský kraj,Benešov,Votice,Olbramovice,"DAVO CAR, s.r.o.",Praha,True,True,False,False,False,True,4.0,2.0,2.0
30,120201,Středočeský kraj,Beroun,Hořovice,Hořovice,"Ekotech Hořovice, s.r.o.",Hořovice,True,True,False,False,False,True,2.0,2.0,5.0
31,120301,Středočeský kraj,Kladno,Kladno,Kladno,Měření 3D spol. s r.o.,Praha,True,True,False,False,False,True,2.0,2.0,5.0
32,120401,Středočeský kraj,Kolín,Kolín,Nebovidy,Clever Cars s.r.o..,Nebovidy,False,True,False,False,False,True,2.0,2.0,3.0
33,120402,Středočeský kraj,Kolín,Kolín,Zásmuky,STK Zásmuky s.r.o.,Praha,True,True,False,False,False,True,4.0,2.0,5.0
34,120403,Středočeský kraj,Kolín,Český Brod,Tuklaty,AUTO HÁJEK s.r.o.,Škvorec,True,True,False,False,False,True,9.0,2.0,4.0
35,120404,Středočeský kraj,Kolín,Kolín,Kolín,Vladimír Coubal,Vitice,True,True,False,False,False,True,2.0,2.0,3.0
36,120501,Středočeský kraj,Kutná Hora,Kutná Hora,Suchdol,Jaroslav Mašín,Suchdol,True,True,False,False,False,True,6.0,2.0,2.0
37,120502,Středočeský kraj,Kutná Hora,Kutná Hora,Kutná Hora,"U N I K O M, a.s.",Kutná Hora,True,True,False,False,False,True,5.0,2.0,2.0
38,120901,Středočeský kraj,Praha-východ,Říčany,Struhařov,Petr Kajuk,Struhařov,True,True,False,False,False,True,2.0,2.0,2.0
39,120903,Středočeský kraj,Praha-východ,Brandýs nad Labem-Stará Boleslav,Brandýs nad Labem-Stará Boleslav,E3F3 s.r.o.,Praha,True,True,False,False,False,True,9.0,2.0,5.0
40,130101,Jihočeský kraj,České Budějovice,České Budějovice,České Budějovice,VAZI s.r.o.,České Budějovice,True,True,False,False,False,True,5.0,2.0,4.0
41,130102,Jihočeský kraj,České Budějovice,České Budějovice,České Budějovice,PASS CB s.r.o.,České Budějovice,True,True,False,False,False,True,9.0,2.0,2.0
42,130401,Vysočina,Pelhřimov,Pelhřimov,Pelhřimov,AAA SME Omikron s.r.o.,Praha,True,True,False,False,False,True,9.0,2.0,5.0
43,130601,Jihočeský kraj,Prachatice,Vimperk,Vacov,Martin Čtvrtník,Vacov,True,True,False,False,False,True,6.0,2.0,2.0
44,130602,Jihočeský kraj,Prachatice,Prachatice,Těšovice,KŮTA AMS s.r.o.,Těšovice,True,True,False,False,False,True,8.0,2.0,2.0
45,130701,Jihočeský kraj,Strakonice,Vodňany,Vodňany,STK VODŇANY s.r.o.,Vodňany,True,True,False,False,False,True,9.0,2.0,5.0
46,130801,Jihočeský kraj,Tábor,Tábor,Bechyně,Ing. Jindřich Kovač,Praha,False,True,False,False,False,True,8.0,2.0,3.0
47,130802,Jihočeský kraj,Tábor,Tábor,Opařany,KAFKA TRANSPORT a.s.,Opařany,True,True,False,False,False,True,8.0,2.0,2.0
48,140301,Karlovarský kraj,Karlovy Vary,Karlovy Vary,Karlovy Vary,Emise-KV s.r.o.,Hory,True,True,False,False,False,True,7.0,2.0,2.0
49,140401,Plzeňský kraj,Klatovy,Klatovy,Klatovy,Jan Holeček,Chlistov,True,True,False,False,False,True,2.0,2.0,2.0

                                        0
Stanice_Cislo                 1409 / 1409
Stanice_Adresa_Kraj           1409 / 1409
Stanice_Adresa_Okres          1409 / 1409
Stanice_Adresa_Orp            1409 / 1409
Stanice_Adresa_Obec           1409 / 1409
Provozovatel_Nazev            1409 / 1409
Provozovatel_Adresa_Obec      1409 / 1409
Provozovatel_Kontakt_Telefon  1409 / 1409
Provozovatel_Kontakt_Email    1409 / 1409
Stk_Pritomno                  1409 / 1409
Adr_Pritomno                  1409 / 1409
SmeZkusebni_Pritomno          1409 / 1409
Sme_Pritomno                  1409 / 1409
Sme_Osvedceni_Kategorie        456 / 1409
Sme_Osvedceni_EmisniSystem    1388 / 1409
Sme_Osvedceni_Palivo          1388 / 1409

shape: (1, 16)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Sta ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Stk ┆ Adr ┆ Sme ┆ Sme ┆ Sme ┆ Sme ┆ Sme_Os │
│ nic ┆ nic ┆ nic ┆ nic ┆ nic ┆ voz ┆ voz ┆ voz ┆ voz ┆ _Pr ┆ _Pr ┆ Zku ┆ _Pr ┆ _Os ┆ _Os ┆ vedcen │
│ e_C ┆ e_A ┆ e_A ┆ e_A ┆ e_A ┆ ova ┆ ova ┆ ova ┆ ova ┆ ito ┆ ito ┆ seb ┆ ito ┆ ved ┆ ved ┆ i_Pali │
│ isl ┆ dre ┆ dre ┆ dre ┆ dre ┆ tel ┆ tel ┆ tel ┆ tel ┆ mno ┆ mno ┆ ni_ ┆ mno ┆ cen ┆ cen ┆ vo     │
│ o   ┆ sa_ ┆ sa_ ┆ sa_ ┆ sa_ ┆ _Na ┆ _Ad ┆ _Ko ┆ _Ko ┆ --- ┆ --- ┆ Pri ┆ --- ┆ i_K ┆ i_E ┆ ---    │
│ --- ┆ Kra ┆ Okr ┆ Orp ┆ Obe ┆ zev ┆ res ┆ nta ┆ nta ┆ boo ┆ boo ┆ tom ┆ boo ┆ ate ┆ mis ┆ list[s │
│ i32 ┆ j   ┆ es  ┆ --- ┆ c   ┆ --- ┆ a_O ┆ kt_ ┆ kt_ ┆ l   ┆ l   ┆ no  ┆ l   ┆ gor ┆ niS ┆ tr]    │
│     ┆ --- ┆ --- ┆ str ┆ --- ┆ str ┆ bec ┆ Tel ┆ Ema ┆     ┆     ┆ --- ┆     ┆ ie  ┆ yst ┆        │
│     ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ efo ┆ il  ┆     ┆     ┆ boo ┆     ┆ --- ┆ em  ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ n   ┆ --- ┆     ┆     ┆ l   ┆     ┆ lis ┆ --- ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ boo ┆     ┆     ┆     ┆     ┆ t[s ┆ lis ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆ l   ┆     ┆     ┆     ┆     ┆ tr] ┆ t[s ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ 110 ┆ Hla ┆ Hla ┆ Hla ┆ Pra ┆ Emi ┆ Pra ┆ tru ┆ tru ┆ fal ┆ fal ┆ fal ┆ tru ┆ ["M ┆ ["N ┆ ["BA", │
│ 301 ┆ vní ┆ vní ┆ vní ┆ ha  ┆ tec ┆ ha  ┆ e   ┆ e   ┆ se  ┆ se  ┆ se  ┆ e   ┆ 1", ┆ ERI ┆ "NM"]  │
│     ┆ měs ┆ měs ┆ měs ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "M2 ┆ ZEN ┆        │
│     ┆ to  ┆ to  ┆ to  ┆     ┆ s.r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ Y", ┆        │
│     ┆ Pra ┆ Pra ┆ Pra ┆     ┆ .o. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ "RI ┆        │
│     ┆ ha  ┆ ha  ┆ ha  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "N2 ┆ ZEN ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "]  ┆ Y"] ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

Provozovatelé se relativně často opakují u různých stanic

In [18]:
sorted(df['Provozovatel_Nazev'].to_list())[:30]

['" PANAM " , spol. s r.o.',
 '"AUTOTOP" spol. s r.o.',
 '"K H K  ŽATEC", s.r.o.',
 '"Stanice technické kontroly Pelhřimov spol. s r.o.',
 '"Stanice technické kontroly Pelhřimov spol. s r.o.',
 '1H Holding s.r.o.',
 '2H Holding, s.r.o.',
 'A M G CENTRUM, s. r. o.',
 'A M G CENTRUM, s. r. o.',
 'A U T O ... s.r.o.',
 'A-STK s.r.o.',
 'A-STK s.r.o.',
 'A-STK s.r.o.',
 'A-STK s.r.o.',
 'A-Z Beroun, s.r.o.',
 'A-Z Beroun, s.r.o.',
 'A1C1 s.r.o.',
 'A1U1 s.r.o.',
 'AAA SME Omikron s.r.o.',
 'AAA SME Theta s.r.o.',
 'AB Auto Brejla s.r.o.',
 'ABA STKáčko s.r.o.',
 'ABA STKáčko s.r.o.',
 'ABERA spol. s r.o.',
 'ABERA spol. s r.o.',
 'ABERA spol. s r.o.',
 'ABERA spol. s r.o.',
 'ABH CAR Praha s.r.o.',
 'AD-auto-elektroopravna, výrobní družstvo',
 'ADIV, spol. s r.o.']

Některým stanicím zjevně chybí hodnoty pro SME přestože ho provozují (podle jejich webových stránek)

In [19]:
display(df['Sme_Osvedceni_EmisniSystem'].value_counts())
short_display(df.filter(pl.col('Sme_Osvedceni_EmisniSystem').is_null()))

shape: (4, 2)
┌────────────────────────────┬───────┐
│ Sme_Osvedceni_EmisniSystem ┆ count │
│ ---                        ┆ ---   │
│ list[str]                  ┆ u32   │
╞════════════════════════════╪═══════╡
│ null                       ┆ 21    │
│ ["RIZENY"]                 ┆ 3     │
│ ["NERIZENY"]               ┆ 1     │
│ ["NERIZENY", "RIZENY"]     ┆ 1384  │
└────────────────────────────┴───────┘

(21, 16)

,Stanice_Cislo,Stanice_Adresa_Kraj,Stanice_Adresa_Okres,Stanice_Adresa_Orp,Stanice_Adresa_Obec,Provozovatel_Nazev,Provozovatel_Adresa_Obec,Provozovatel_Kontakt_Telefon,Provozovatel_Kontakt_Email,Stk_Pritomno,Adr_Pritomno,SmeZkusebni_Pritomno,Sme_Pritomno,Sme_Osvedceni_Kategorie,Sme_Osvedceni_EmisniSystem,Sme_Osvedceni_Palivo
0,111114,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,BĚLOHRADSKÝ spol. s r.o.,Praha,True,True,False,False,False,True,NaN,NaN,NaN
1,111134,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,DEKRA CZ a.s.,Praha,True,True,False,False,False,True,NaN,NaN,NaN
2,111155,Hlavní město Praha,Hlavní město Praha,Hlavní město Praha,Praha,STK CZ s.r.o.,Praha,False,True,False,False,False,True,NaN,NaN,NaN
3,420324,Středočeský kraj,Kladno,Kladno,Kladno,AUTOCENTRUM NEVECOM spol. s r.o.,Kladno,True,True,False,False,False,True,NaN,NaN,NaN
4,421018,Středočeský kraj,Praha-západ,Černošice,Mníšek pod Brdy,AUTOSERVIS-DIESEL SERVIS LIBOVICKÝ JIŘÍ,MNÍŠEK POD BRDY,True,True,False,False,False,True,NaN,NaN,NaN
5,450713,Ústecký kraj,Louny,Podbořany,Lubenec,"R + B Auto control, spol. s r.o.",Plzeň,True,True,False,False,False,True,NaN,NaN,NaN
6,460304,Pardubický kraj,Chrudim,Chrudim,Dřenice,Auto Hybeš s.r.o.,Dřenice,False,True,False,False,False,True,NaN,NaN,NaN
7,460636,Pardubický kraj,Pardubice,Pardubice,Pardubice,TOYOTA TSUSHO PRAHA s.r.o.,Čestlice,False,True,False,False,False,True,NaN,NaN,NaN
8,470220,Jihomoravský kraj,Brno-město,Brno,Brno,Ing. Jiří Fasora,Brno,True,True,False,False,False,True,NaN,NaN,NaN
9,470244,Jihomoravský kraj,Brno-město,Brno,Brno,"Autocentrum ROS, a.s.",Brno,True,True,False,False,False,True,NaN,NaN,NaN
10,480348,Moravskoslezský kraj,Karviná,Karviná,Karviná,"STK EMISE, s.r.o.",Karviná,True,True,False,False,False,True,NaN,NaN,NaN
11,480404,Moravskoslezský kraj,Nový Jičín,Kopřivnice,Kopřivnice,Autoservis Rudolf Vašek s.r.o.,Kopřivnice,True,True,False,False,False,True,NaN,NaN,NaN
12,520204,Středočeský kraj,Beroun,Beroun,Loděnice,"Iveco Truck Centrum, s.r.o.",Loděnice,True,True,False,False,False,True,NaN,NaN,NaN
13,560404,Královéhradecký kraj,Jičín,Jičín,Úlibice,Lužanská zemědělská a.s.,Lužany,True,True,False,False,False,True,NaN,NaN,NaN
14,560810,Liberecký kraj,Semily,Turnov,Turnov,"KONTAKT - služby motoristům, spol. s r.o.",Turnov,False,True,False,False,False,True,NaN,NaN,NaN
15,570205,Jihomoravský kraj,Brno-město,Brno,Brno,"Dopravní podnik města Brna, a.s.",Brno,True,True,False,False,False,True,NaN,NaN,NaN
16,570401,Jihomoravský kraj,Břeclav,Břeclav,Velké Bílovice,"AGROSERVIS, spol. s r.o.",Velké Bílovice,True,True,False,False,False,True,NaN,NaN,NaN
17,570517,Zlínský kraj,Zlín,Otrokovice,Napajedla,SAMOHÝL MB a.s.,Zlín,True,True,False,False,False,True,NaN,NaN,NaN
18,580812,Olomoucký kraj,Přerov,Hranice,Hranice,Dušan Vika,Hranice,True,True,False,False,False,True,NaN,NaN,NaN
19,6614,Královéhradecký kraj,Jičín,Jičín,Úlibice,STK Jičín s.r.o.,Úlibice,True,True,True,False,False,False,NaN,NaN,NaN
20,6618,Pardubický kraj,Chrudim,Chrudim,Slatiňany,STK EURO s.r.o.,Slatiňany,False,True,True,False,False,True,NaN,NaN,NaN