In [1]:
import os
import time
import random
import warnings
from datetime import date

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from lxml import etree # type: ignore <- pylance milně hlásí chybu
from pathlib import Path
import time
import sys
import polars as pl
import polars.selectors as cs
import json
import pickle
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import matplotlib.patheffects as path_effects
from ydata_profiling import ProfileReport
import geopandas as gpd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA
from pyod.models.iforest import IForest
from pyod.models.ecod import ECOD


current_dir = Path(__file__).resolve().parent if "__file__" in locals() else Path.cwd()
sys.path.append(str(current_dir.parent))
from utils import *
from schemas import *
from clean import *
from visualisation_utils import *

pl.Config.set_tbl_cols(-1)
os.chdir(r'E:\CVUT_BAP')
# os.chdir(r'C:\Users\adamp\Projects\CVUT_BAP')
SEED=42
PRINT = True

# Nacteni dat
- pro anomalie neni VIN brano v potaz

In [2]:
lf_prohlidky = pl.scan_parquet(r"E:\CVUT_BAP\kod\data\processed\mereni.parquet")
lf_mereni = pl.scan_parquet(r"E:\CVUT_BAP\kod\data\processed\prohlidky.parquet")
lf = lf_prohlidky.join(lf_mereni, on='CisloProtokolu', how='inner')

In [3]:
# print(lf.collect_schema().names())

In [4]:
df = lf.filter(pl.col('Vysledek_Vyhovuje') == True).drop(['Vozidlo_Vin', 'Vysledek_Vyhovuje']).collect().sample(n=100_000, seed=SEED)

In [5]:
df.write_parquet(r"E:\CVUT_BAP\kod\data\processed\anomaly_sample.parquet")

# Priprava dat pro analyzu

In [6]:
def preprocess_anomalies_pipeline(df, freq_threshold=0.001, custom_cat_cols=None):
    # Zachování ID protokolů pro pozdější identifikaci nálezů
    protocol_ids = df.select("CisloProtokolu")
    df_working = df.drop("CisloProtokolu")

    # Převod seznamů na numerický počet prvků (např. počet závad)
    list_cols = [n for n, t in zip(df_working.columns, df_working.dtypes) if t == pl.List]
    df_working = df_working.with_columns([
        pl.col(c).list.len().fill_null(0).alias(f"{c}_count") for c in list_cols
    ]).drop(list_cols)

    print('1')

    # Identifikace sloupců pro kategorické kódování
    base_cats = [n for n, t in zip(df_working.columns, df_working.dtypes) if t in [pl.String, pl.Categorical]]
    cat_cols = list(set(base_cats + custom_cat_cols)) if custom_cat_cols else base_cats
    
    total_rows = df_working.height
    for col in cat_cols:
        if col not in df_working.columns:
            continue
        print(col)
            
        # Výpočet relativních frekvencí výskytu hodnot
        counts = df_working.group_by(col).len().with_columns(
            (pl.col("len") / total_rows).alias("rel_freq")
        )
        
        # Filtrace dominantních kategorií pro binární příznaky
        top_categories = counts.filter(pl.col("rel_freq") >= freq_threshold).select(col).to_series().to_list()
        
        if len(top_categories) > 0:
            for cat in top_categories:
                # Ošetření null hodnot a formátování názvů nových sloupců
                if cat is None:
                    condition = pl.col(col).is_null()
                    safe_name = "null"
                else:
                    condition = pl.col(col) == cat
                    safe_name = str(cat).replace(" ", "_").replace("-", "_").lower()
                
                df_working = df_working.with_columns(
                    condition.cast(pl.Int8).alias(f"{col}_is_{safe_name}")
                )
        
        # Přidání rarity score zachycující vzácnost výskytu
        df_working = df_working.join(counts.select([col, "rel_freq"]), on=col, how="left")
        df_working = df_working.with_columns(
            pl.col("rel_freq").fill_null(0.0).alias(f"{col}_rarity_score")
        ).drop([col, "rel_freq"])

    print('2')
    # Normalizace logických hodnot na numerické formáty
    df_working = df_working.with_columns([
        pl.col(pl.Boolean).fill_null(False).cast(pl.Int8)
    ])

    # Výběr všech číselných sloupců pro finální škálování
    numeric_cols = [n for n, t in zip(df_working.columns, df_working.dtypes) if t.is_numeric()]
    
    # Odstranění záporných hodnot z reálných měření
    df_working = df_working.with_columns([
        pl.col(c).clip(lower_bound=0) for c in numeric_cols
    ])
    print('3')

    # Konverze na Numpy matici
    X = df_working.select(numeric_cols).to_numpy()
    
    # První stupeň škálování na sjednocený rozsah
    mms = MinMaxScaler(feature_range=(0, 1))
    X_transformed = mms.fit_transform(X)
    print('4')
    
    # Geometrické oddělení chybějících údajů konstantou pod minimem
    X_transformed[np.isnan(X_transformed)] = -1
    
    # Finální standardizace distribucí pro výpočet hlavních komponent
    ss = StandardScaler()
    X_final = ss.fit_transform(X_transformed)
    
    return X_final, protocol_ids

# Seznam číselných sloupců s kategorickým významem
cat_numeric_cols = [
    'Prohlidka_OdpovednaOsoba', 
    'Prohlidka_Stanice_Cislo', 
    'Emise_OdpovednaOsoba', 
    'Vysledek_RidiciJednotkaStav', 
    'Vysledek_Mil', 
    'Obd_KontrolaMil'
] + [col for col in df.columns if col.endswith('_Vysledek') and df[col].dtype.is_numeric()]

# Transformace datové sady
X, id = preprocess_anomalies_pipeline(df, custom_cat_cols=cat_numeric_cols)

1
Nafta_Mereni2_TPS_Vysledek
Nafta_Mereni3_Kourivost_Vysledek
Prohlidka_Stanice_Obec
Benzin_OtackyZvysene_O2_Vysledek
Nafta_MereniPrumer_Kourivost_Vysledek
Prohlidka_OdpovednaOsoba
Nafta_Mereni2_Kourivost_Vysledek
Nafta_MereniPrumer_TPS_Vysledek
Nafta_MereniPrumer_Teplota_Vysledek
Obd_KomunikacniProtokol
Nafta_Mereni2_CasAkcelerace_Vysledek
Benzin_OtackyVolnobezne_N_Vysledek
Nafta_Mereni1_Kourivost_Vysledek
Emise_OdpovednaOsoba
Nafta_Mereni3_CasAkcelerace_Vysledek
MericiPristroj_Verze
Benzin_OtackyVolnobezne_TPS_Vysledek
Nafta_Mereni0_Teplota_Vysledek
Benzin_OtackyZvysene_CO2_Vysledek
Benzin_OtackyVolnobezne_CO2_Vysledek
Nafta_Mereni3_Teplota_Vysledek
Nafta_Mereni0_TPS_Vysledek
Nafta_Mereni2_OtackyPrebehove_Vysledek
Nafta_Mereni1_OtackyVolnobezne_Vysledek
Benzin_OtackyVolnobezne_NOX_Vysledek
Nafta_Mereni3_TPS_Vysledek
Nafta_Mereni2_Teplota_Vysledek
Nafta_Mereni1_OtackyPrebehove_Vysledek
Emise_ZakladniPalivo
Vozidlo_Znacka
Registrace_Stat
Benzin_OtackyVolnobezne_O2_Vysledek
Nafta_MereniPrumer_OtackyVolnobezne_Vysledek
Nafta_Mereni0_OtackyVolnobezne_Vysledek
Nafta_Mereni1_CasAkcelerace_Vysledek
Benzin_OtackyVolnobezne_COCOOR_Vysledek
Benzin_OtackyZvysene_COCOOR_Vysledek
Nafta_Mereni1_TPS_Vysledek
Prohlidka_Stanice_Kraj
MericiPristroj_Typ
Vozidlo_Druh
Nafta_Mereni3_OtackyVolnobezne_Vysledek
Vozidlo_ObchodniOznaceni
Nafta_Mereni0_Kourivost_Vysledek
Nafta_Mereni0_CasAkcelerace_Vysledek
Vysledek_RidiciJednotkaStav
Nafta_Mereni0_OtackyPrebehove_Vysledek
Nafta_Mereni3_OtackyPrebehove_Vysledek
Obd_KontrolaMil
Nafta_Mereni2_OtackyVolnobezne_Vysledek
Vysledek_Mil
Nafta_MereniPrumer_OtackyPrebehove_Vysledek
Benzin_OtackyZvysene_LAMBDA_Vysledek
Prohlidka_Stanice_Cislo
Benzin_OtackyVolnobezne_CO_Vysledek
Benzin_OtackyVolnobezne_LAMBDA_Vysledek
Benzin_OtackyZvysene_TPS_Vysledek
Benzin_OtackyZvysene_NOX_Vysledek
Vozidlo_TypMotoru
Benzin_OtackyZvysene_HC_Vysledek
Benzin_OtackyZvysene_N_Vysledek
MericiPristroj_Vyrobce
Benzin_OtackyZvysene_CO_Vysledek
Nafta_MereniPrumer_CasAkcelerace_Vysledek
MericiPristroj_VerzeSoftware
Nafta_Mereni1_Teplota_Vysledek
Benzin_OtackyVolnobezne_HC_Vysledek
MericiPristroj_OBD
Prohlidka_Stanice_ORP
Vozidlo_Provedeni
2
3
4

In [7]:
X.shape

(100000, 2236)

In [8]:
# 1. Redukce dimenzionality (PCA)
print("Zahajuji PCA pro redukci dimenzionality...")
pca = PCA(n_components=50, random_state=42)
X_pca = pca.fit_transform(X)
print(f"PCA dokončeno. Vysvětlený rozptyl: {pca.explained_variance_ratio_.sum():.4f}")

# 2. Detekce anomálií (Isolation Forest)
print("Trénuji Isolation Forest na redukovaných datech...")
clf = IForest(contamination=0.01, n_jobs=-1, random_state=42)
clf.fit(X_pca)
print("Model Isolation Forest natrénován.")

# 3. Mapování výsledků na ID protokolů
print("Propojuji vypočtená skóre s identifikátory...")
vysledky_map = id.with_columns([
    pl.Series("anomaly_score", clf.decision_scores_),
    pl.Series("is_anomaly", clf.labels_)
])

# 4. Filtrace a spojení s původním dataframe
print("Filtruji anomálie a spojuji s původními daty...")
anomali_ids = vysledky_map.filter(pl.col("is_anomaly") == 1).select("CisloProtokolu")

# Vytvoření finálního dataframe se všemi původními sloupci
df_anomalie = df.join(
    anomali_ids, on="CisloProtokolu", how="inner"
).join(
    vysledky_map.select(["CisloProtokolu", "anomaly_score"]), 
    on="CisloProtokolu", 
    how="left"
).sort("anomaly_score", descending=True)

print(f"Hotovo. Celkem nalezeno {df_anomalie.height} anomálií.")
short_display(df_anomalie)

Zahajuji PCA pro redukci dimenzionality...
PCA dokončeno. Vysvětlený rozptyl: 0.2823
Trénuji Isolation Forest na redukovaných datech...
Model Isolation Forest natrénován.
Propojuji vypočtená skóre s identifikátory...
Filtruji anomálie a spojuji s původními daty...
Hotovo. Celkem nalezeno 1000 anomálií.
(1000, 224)

,CisloProtokolu,MericiPristroj_Vyrobce,MericiPristroj_Typ,MericiPristroj_Verze,MericiPristroj_OBD,MericiPristroj_VerzeSoftware,Vysledek_VisualniKontrola,Vysledek_Readiness,Vysledek_RidiciJednotkaStav,Vysledek_Mil,...,AdrCast_Pritomno,TskCast_Pritomno,Vysledek_Odometr,AdministrativneOpraveno,Doba_Trvani_Prohlidky,Doba_Trvani_Emisi,Stari_Vozidla_Let,Zahajeni_Sin,Zahajeni_Cos,anomaly_score
0,CZ-470118-19-04-0286,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,118426,False,12.966667,6.450000,19.085558,-0.811165,-0.584817,0.057636
1,CZ-470118-20-10-0106,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,141970,False,8.716667,7.683333,21.445585,-0.527029,-0.849848,0.057636
2,CZ-470118-20-07-0149,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,167689,False,9.816667,7.800000,20.164271,0.986757,-0.162207,0.054915
3,CZ-470118-19-04-0023,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,50513,False,22.350000,7.983333,19.101985,-0.659225,-0.751945,0.054488
4,CZ-470118-21-09-0294,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,78268,False,10.833333,8.983333,26.724162,-0.393223,-0.919443,0.051810
5,CZ-470118-19-07-0063,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,71277,False,9.000000,7.050000,6.017796,0.239441,-0.970911,0.050467
6,CZ-470118-19-04-0184,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,NaN,2.0,...,False,False,62251,False,101.550000,10.183333,37.897331,0.729703,-0.683764,0.049495
7,CZ-470403-19-08-0232,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,168076,False,21.483333,20.733333,21.560575,0.818650,-0.574293,0.049262
8,CZ-420820-23-06-0355,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,None,V2.5.2 09/2022,True,None,1.0,2.0,...,False,False,127886,False,94.033333,9.050000,22.012320,0.496839,-0.867843,0.048905
9,CZ-420820-23-06-0195,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,None,V2.5.2 09/2022,True,None,1.0,2.0,...,False,False,134947,False,117.633333,14.783333,22.113621,-0.293302,-0.956020,0.048781
10,CZ-470403-19-05-0520,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,250633,False,12.283333,9.633333,19.200548,0.544933,-0.838480,0.048622
11,CZ-470403-19-05-0470,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,87561,False,38.716667,11.100000,19.934292,0.262061,-0.965051,0.048199
12,CZ-470403-20-07-0221,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,197249,False,14.633333,12.600000,20.317591,0.889846,-0.456262,0.048199
13,CZ-470118-21-01-0100,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,97160,False,10.216667,8.450000,10.294319,-0.515175,-0.857085,0.047824
14,CZ-470118-21-01-0091,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,90788,False,9.300000,6.816667,9.995893,0.370159,-0.928968,0.047480
15,CZ-470118-19-12-0085,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,148148,False,12.516667,8.183333,6.157426,0.847483,-0.530823,0.047422
16,CZ-470118-19-11-0150,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,22646,False,9.500000,7.733333,3.890486,0.883608,-0.468228,0.047370
17,CZ-470403-20-02-0223,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,198944,False,24.250000,23.666667,20.153320,0.873101,-0.487539,0.046526
18,CZ-470118-22-11-0211,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,None,1.0,True,None,NaN,NaN,...,False,False,60523,False,33.983333,30.333333,36.698152,0.999659,0.026110,0.046464
19,CZ-470118-20-02-0003,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,209279,False,12.650000,9.416667,9.826146,0.944622,-0.328161,0.046388
20,CZ-470118-20-06-0338,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,131477,False,8.400000,6.433333,9.971253,0.766929,-0.641732,0.046295
21,CZ-470118-21-06-0248,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,59330,False,8.933333,7.800000,5.971253,-0.273510,-0.961869,0.046148
22,CZ-470403-20-11-0027,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,264826,False,19.400000,18.600000,22.362765,-0.114927,-0.993374,0.046105
23,CZ-470403-20-03-0289,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,220704,False,26.250000,25.633333,22.499658,0.750808,-0.660521,0.046105
24,CZ-420820-23-03-0341,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,None,V2.5.2 09/2022,True,None,1.0,2.0,...,False,False,150125,False,67.816667,13.350000,26.778919,0.963258,-0.268576,0.046000
25,CZ-470403-20-07-0344,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,164980,False,20.550000,19.433333,18.381930,-0.356976,-0.934113,0.045445
26,CZ-470118-23-08-0248,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,None,1.0,True,None,1.0,NaN,...,False,False,187339,False,13.133333,11.616667,23.195072,0.617582,-0.786506,0.045257
27,CZ-470118-19-04-0348,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,None,V1.21,True,None,1.0,2.0,...,False,False,118567,False,11.666667,7.750000,19.983573,-0.412704,-0.910865,0.044956
28,CZ-470118-20-06-0186,Bosch,RTM430,RTM v2.0 02.08.96 $1172,KTS540,V1.21,True,False,1.0,2.0,...,False,False,221378,False,15.816667,10.533333,7.885010,0.972879,-0.231315,0.044580
29,CZ-470118-19-07-0323,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,False,1.0,2.0,...,False,False,207289,False,10.800000,8.800000,11.800137,-0.395556,-0.918442,0.044443
30,CZ-470118-19-03-0095,Bosch,RTM430,RTM v2.0 02.08.96 $1172,KTS540,V1.21,True,True,1.0,2.0,...,False,False,399569,False,20.283333,18.300000,14.480493,0.448438,-0.893814,0.044355
31,CZ-470118-25-06-0268,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS560,1.1,True,True,1.0,2.0,...,False,False,63245,False,12.716667,11.466667,4.032854,0.893873,-0.448320,0.044294
32,CZ-470118-21-03-0197,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,75419,False,8.366667,7.166667,10.945927,0.998727,-0.050445,0.043063
33,CZ-470118-19-05-0259,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,182884,False,8.966667,6.900000,18.239562,0.926397,-0.376548,0.042907
34,CZ-470118-21-04-0064,Bosch,RTM430,RTM v2.0 02.08.96 $1172,KTS540,V1.21,True,True,1.0,2.0,...,False,False,84667,False,12.533333,10.866667,12.030116,0.997692,-0.067900,0.042735
35,CZ-470118-21-12-0104,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,21433,False,8.916667,6.850000,3.964408,0.969019,-0.246987,0.042421
36,CZ-470118-20-06-0089,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,59778,False,9.100000,6.983333,4.273785,0.723753,-0.690059,0.042191
37,CZ-470118-21-06-0270,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,146488,False,7.600000,6.616667,15.600274,-0.403765,-0.914863,0.042108
38,CZ-470403-19-12-0233,BOSCH,BEA450,SW-BEA-PC CZ V1.21,ne,CZ V1.21,True,None,NaN,NaN,...,False,False,341966,False,21.450000,20.983333,20.955510,0.772970,-0.634443,0.041917
39,CZ-470118-23-06-0102,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,None,1.0,True,None,1.0,NaN,...,False,False,93942,False,9.350000,8.016667,26.839151,0.880372,-0.474283,0.041902
40,CZ-470118-20-10-0274,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,24103,False,9.116667,7.200000,4.183436,0.841666,-0.539999,0.041739
41,CZ-470118-20-02-0009,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,105710,False,12.416667,10.750000,14.143737,0.718098,-0.695942,0.041525
42,CZ-470118-20-02-0206,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,201754,False,13.616667,10.450000,17.453799,0.863355,-0.504596,0.041525
43,CZ-450111-24-05-0206,AVL DiTEST GmbH,AVL DiSmoke 480,V2.5 07/2011,AVL OBD 1000,V2.5.2 09/2022,True,None,1.0,2.0,...,False,False,445084,False,11.300000,10.866667,22.940452,0.899836,-0.436228,0.041370
44,CZ-450111-23-10-0128,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,None,1.0,2.0,...,False,False,87434,False,7.533333,7.166667,22.193018,0.399022,-0.916941,0.041194
45,CZ-470118-22-08-0312,Bosch,BEA 950,/ BEA070 V1.19 CFFE0424,None,1.0,True,None,1.0,NaN,...,False,False,230967,False,12.600000,10.366667,19.274470,0.947662,-0.319277,0.041138
46,CZ-470118-23-06-0210,Bosch,BEA 950,/ BEA070 V1.19 CFFE0424,None,1.0,True,None,1.0,NaN,...,False,False,302137,False,17.166667,14.816667,20.689938,0.999190,-0.040242,0.041138
47,CZ-470118-20-06-0309,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,134383,False,7.633333,5.966667,13.957563,0.590125,-0.807312,0.041106
48,CZ-470118-20-02-0048,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,146042,False,9.166667,6.850000,9.946612,0.496342,-0.868127,0.040775
49,CZ-470118-21-07-0086,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,140090,False,8.683333,6.966667,13.286790,0.999343,-0.036249,0.040124

In [20]:
short_display(df.filter(pl.col('Benzin_PocetVyusteni') == 1))
rucni_cols = [col for col in df_anomalie.columns if 'RucniZadani' in col]
short_display(df_anomalie.filter(~pl.any_horizontal(pl.col(rucni_cols).fill_null(False) == True)).filter(pl.col('EmisniSystem') == 'Rizeny_Obd'))

(54122, 223)

,CisloProtokolu,MericiPristroj_Vyrobce,MericiPristroj_Typ,MericiPristroj_Verze,MericiPristroj_OBD,MericiPristroj_VerzeSoftware,Vysledek_VisualniKontrola,Vysledek_Readiness,Vysledek_RidiciJednotkaStav,Vysledek_Mil,...,TechnickaCast_Pritomno,AdrCast_Pritomno,TskCast_Pritomno,Vysledek_Odometr,AdministrativneOpraveno,Doba_Trvani_Prohlidky,Doba_Trvani_Emisi,Stari_Vozidla_Let,Zahajeni_Sin,Zahajeni_Cos
0,CZ-410408-19-12-0020,BOSCH,BEA050,SW-BEA-PC CZ V1.21,ano,CZ V1.21,True,True,1.0,2.0,...,False,False,False,126198,False,12.533333,8.533333,5.957563,0.282365,-0.959307
1,CZ-450402-20-08-0031,BRAIN BEE,AGS-200,-,ano,2019.0.1,True,False,1.0,2.0,...,False,False,False,164727,False,12.766667,8.200000,11.107461,-0.371479,-0.928442
2,CZ-480764-21-06-0256,BOSCH,BEA050,SW-BEA-PC CZ V1.21,ano,CZ V1.21,True,True,1.0,2.0,...,False,False,False,95131,False,14.483333,14.083333,4.002738,-0.558042,-0.829812
3,CZ-420940-21-12-0758,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL VCI 1000,V1.41 10/2014,True,True,1.0,2.0,...,False,False,False,81654,False,173.433333,10.350000,3.983573,0.390166,-0.920744
4,CZ-410533-24-09-0491,Bosch,BEA060,BEA060 V1.14 6E795EEC / AMM B6 F54B /,KTS560,1.1,True,True,1.0,2.0,...,False,False,False,88164,False,7.183333,6.216667,3.994524,0.292859,-0.956156
5,CZ-110903-25-07-0123,ATAL s.r.o.,AT505,-,R+OBD,3.08.3,True,True,1.0,2.0,...,False,False,False,50849,False,9.066667,7.750000,8.260096,0.983845,-0.179021
6,CZ-3765-25-08-0345,BRAIN BEE,-,-,-,-,True,True,1.0,1.0,...,True,False,False,93353,False,56.183333,17.883333,65.798768,0.635869,-0.771797
7,CZ-471117-19-05-0010,BRAIN BEE,AGS-200,-,None,2019.0.1,True,None,1.0,2.0,...,False,False,False,141952,False,116.883333,13.216667,18.190281,0.938796,-0.344474
8,CZ-470530-22-01-0015,ActiaCZ,AT505,sw: 2.04.3,ne,sw: 2.04.3,True,None,NaN,2.0,...,False,False,False,135492,False,13.100000,7.283333,22.157426,0.528785,-0.848756
9,CZ-460214-21-08-1048,Bosch,BEA050,BEA V2.02 3AA30592 / AMM 000-B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,False,53773,False,15.483333,14.833333,3.312799,-0.970627,-0.240589
10,CZ-460219-23-01-0045,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,False,1.0,2.0,...,False,False,False,237111,False,84.733333,83.850000,20.487337,0.130217,-0.991486
11,CZ-481023-22-08-0035,ACTIA CZ s.r.o.,AT505,-,R+OBD,3.05.3,True,True,1.0,2.0,...,False,False,False,189063,False,7.350000,5.800000,15.770021,0.714639,-0.699493
12,CZ-450505-20-10-0052,Bosch,BEA055,BEA060 V1.14 6E795EEC / AMM B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,False,82762,False,13.950000,12.500000,9.826146,-0.971050,-0.238874
13,CZ-430520-19-10-0282,Bosch,BEA050,BEA V2.02 3AA30592 / AMM 000-B6 F54B,KTS560,V1.21,True,False,1.0,2.0,...,False,False,False,134150,False,8.850000,8.200000,13.423682,0.902087,-0.431554
14,CZ-511015-25-07-0138,MAHLE,AGS-200,-,ano,2021.0.1,True,True,1.0,2.0,...,False,False,False,222551,False,6.550000,6.016667,21.880903,0.338315,-0.941033
15,CZ-480714-21-10-0842,Bosch,BEA050,BEA V2.02 3AA30592 / AMM 000-B6 F54B,KTS560,V1.21,True,True,1.0,2.0,...,False,False,False,148957,False,50.783333,20.933333,10.220397,0.822768,-0.568377
16,CZ-560406-24-01-0094,BRAIN BEE,AGS-200,None,EOBD,210202000001,True,True,1.0,2.0,...,False,False,False,53012,False,15.483333,13.016667,3.895962,0.012990,-0.999916
17,CZ-450920-19-04-0273,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL VCI 1000,V1.41 10/2014,True,True,1.0,2.0,...,False,False,False,173116,False,6.483333,4.433333,13.938398,0.470497,-0.882402
18,CZ-440324-20-09-0257,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.6 04/2019,True,True,1.0,2.0,...,False,False,False,111095,False,9.666667,7.516667,4.210815,-0.499608,-0.866252
19,CZ-480811-20-10-0043,BRAIN BEE,AGS-200,-,ano,2019.0.1,True,False,1.0,2.0,...,False,False,False,132383,False,15.133333,14.633333,17.908282,0.363511,-0.931590
20,CZ-460821-23-06-0142,MAHLE,AGS-200,-,ano,2021.0.1,True,True,1.0,2.0,...,False,False,False,136005,False,17.900000,17.400000,9.138946,-0.161398,-0.986889
21,CZ-580913-20-12-0122,BRAIN BEE,AGS-200,-,None,2020.0.1,True,None,1.0,2.0,...,False,False,False,82622,False,36.716667,24.233333,20.120465,0.523552,-0.851994
22,CZ-420932-24-05-0485,Bosch,BEA055,BEA060 V1.14 6E795EEC / AMM B6 F54B /,KTS540,1.0,True,False,1.0,2.0,...,False,False,False,227626,False,49.683333,13.066667,17.694730,0.381185,-0.924499
23,CZ-530114-20-12-0039,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,None,V2.4.6 04/2019,True,None,NaN,2.0,...,False,False,False,40066,False,8.666667,6.583333,35.956194,-0.850268,-0.526349
24,CZ-480607-20-03-0067,ActiaCZ,AT505,-,R+OBD,2.07.3,True,True,1.0,2.0,...,False,False,False,33383,False,19.350000,11.816667,9.993155,-0.264029,-0.964515
25,CZ-440722-24-09-0191,ATAL s.r.o.,AT505,None,---,3.07.3,True,None,NaN,NaN,...,False,False,False,107428,False,9.966667,9.716667,25.431896,-0.373933,-0.927456
26,CZ-430826-22-06-0475,ACTIA CZ s.r.o.,AT505,-,R+OBD,3.05.3,True,False,1.0,2.0,...,False,False,False,184314,False,11.950000,10.850000,13.941136,0.926908,-0.375289
27,CZ-550811-22-08-0051,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.0 10/2021,True,True,1.0,2.0,...,False,False,False,189180,False,11.416667,10.583333,20.232717,-0.592470,-0.805592
28,CZ-421024-25-03-1035,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V3.0.4 12/2024,True,True,3.0,2.0,...,False,False,False,278389,False,5.800000,5.383333,12.041068,-0.499883,-0.866093
29,CZ-420219-24-09-0113,Bosch,BEA060,BEA060 V1.14 6E795EEC / AMM B6 F54B /,KTS560,1.1,True,True,1.0,2.0,...,False,False,False,89386,False,43.716667,12.166667,3.983573,-0.872169,-0.489204
30,CZ-580729-24-03-0031,SUN,DGA 1500,-,None,2021.0.1,True,True,1.0,2.0,...,False,False,False,154073,False,19.683333,17.266667,9.615332,0.929956,-0.367671
31,CZ-3122-22-11-1435,ACTIA CZ s.r.o.,AT505,-,R+OBD,3.05.3,True,True,1.0,2.0,...,True,False,False,189946,False,324.683333,10.716667,19.457906,0.907109,-0.420895
32,CZ-3206-24-04-0431,Bosch,BEA050,BEA V2.02 3AA30592 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1.0,2.0,...,True,False,False,198580,False,26.333333,4.983333,19.843943,0.809004,-0.587803
33,CZ-440326-21-02-0862,Bosch,BEA055,BEA060 V1.14 6E795EEC / AMM B6 F54B,KTS540,V1.21,True,True,1.0,2.0,...,False,False,False,246646,False,9.833333,6.766667,13.251198,-0.107319,-0.994225
34,CZ-470299-22-11-1461,MAHLE,AGS-200,-,None,2021.0.1,True,None,1.0,2.0,...,False,False,False,202061,False,223.500000,6.283333,23.895962,0.573400,-0.819275
35,CZ-420329-21-10-0561,BOSCH,BEA055,SW-BEA-PC CZ V1.21,ano,CZ V1.21,True,True,1.0,2.0,...,False,False,False,123943,False,14.316667,13.766667,18.403833,0.927876,-0.372890
36,CZ-411045-19-01-0043,ActiaCZ,AT505,-,R,2.05.3,True,None,1.0,2.0,...,False,False,False,259450,False,18.600000,17.050000,23.044490,0.639221,-0.769023
37,CZ-440703-19-02-0046,BRISK,JT283A,-,None,2019.0.1,True,None,1.0,2.0,...,False,False,False,100630,False,21.066667,20.500000,20.355921,0.461308,-0.887240
38,CZ-470806-20-08-0081,AVL DiTEST GmbH,AVL Gas 1000,None,ano,V2.4.6,True,True,1.0,2.0,...,False,False,False,28311,False,13.416667,10.383333,3.980835,0.308388,-0.951261
39,CZ-410910-25-10-0116,AVL DiTEST GmbH,AVL Gas 1000,V1.51 12/2019,AVL OBD 1000,V3.0.5 01/2025,True,True,1.0,2.0,...,False,False,False,200299,False,23.400000,22.016667,19.504449,-0.950157,-0.311772
40,CZ-571313-24-03-0693,MAHLE,AGS-200,-,None,2021.0.1,True,None,1.0,2.0,...,False,False,False,172735,False,6.916667,6.250000,25.623546,0.222292,-0.974980
41,CZ-530604-24-04-0156,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,None,V2.5.0 10/2021,True,None,1.0,2.0,...,False,False,False,280261,False,9.100000,6.050000,24.358658,-0.318679,-0.947863
42,CZ-421039-25-06-0455,ATAL s.r.o.,AT505,-,R+OBD,3.08.3,True,True,1.0,2.0,...,False,False,False,48709,False,78.833333,5.833333,15.770021,0.774812,-0.632192
43,CZ-480428-22-11-0545,Bosch,BEA050,BEA V2.02 3AA30592 / AMM 000-B6 F54B /,KTS560,1.0,True,True,1.0,2.0,...,False,False,False,110205,False,14.283333,9.966667,13.990418,-0.773221,-0.634137
44,CZ-520403-22-02-0118,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1.0,2.0,...,False,False,False,91909,False,20.683333,16.433333,17.960301,0.234466,-0.972124
45,CZ-530607-25-04-0100,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS560,1.0,True,True,1.0,2.0,...,False,False,False,160971,False,15.066667,13.500000,18.551677,0.575996,-0.817452
46,CZ-420940-20-05-0250,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL VCI 1000,V1.41 10/2014,True,True,1.0,2.0,...,False,False,False,147782,False,70.800000,5.966667,11.991786,0.793903,-0.608045
47,CZ-470906-25-12-0121,ATAL s.r.o.,AT505,-,R+OBD,3.08.3,True,True,1.0,2.0,...,False,False,False,58256,False,9.716667,8.933333,5.976728,0.278491,-0.960439
48,CZ-560505-20-01-0014,ActiaCZ,AT505,None,ne,2.07.3,True,None,NaN,NaN,...,False,False,False,141126,False,27.666667,13.866667,18.759754,-0.411894,-0.911232
49,CZ-430834-26-01-0153,Bosch,BEA055,BEA060 V1.14 6E795EEC / AMM B6 F54B,KTS560,1.1,True,True,1.0,2.0,...,False,False,False,154457,False,50.166667,24.050000,20.744695,0.903135,-0.429356

(357, 224)

,CisloProtokolu,MericiPristroj_Vyrobce,MericiPristroj_Typ,MericiPristroj_Verze,MericiPristroj_OBD,MericiPristroj_VerzeSoftware,Vysledek_VisualniKontrola,Vysledek_Readiness,Vysledek_RidiciJednotkaStav,Vysledek_Mil,...,AdrCast_Pritomno,TskCast_Pritomno,Vysledek_Odometr,AdministrativneOpraveno,Doba_Trvani_Prohlidky,Doba_Trvani_Emisi,Stari_Vozidla_Let,Zahajeni_Sin,Zahajeni_Cos,anomaly_score
0,CZ-470118-24-08-0110,Bosch,BEA 950,/ BEA070 V1.19 CFFE0424,KTS540,1.0,True,True,1,2,...,False,False,283417,False,12.550000,10.450000,16.114990,0.921602,-0.388136,0.039640
1,CZ-420820-25-10-0137,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V3.0.5 01/2025,True,True,1,2,...,False,False,162416,False,47.716667,7.816667,10.288843,-0.732386,-0.680890,0.039013
2,CZ-420820-25-10-0128,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V3.0.5 01/2025,True,True,1,2,...,False,False,74725,False,48.316667,13.066667,10.390144,-0.362091,-0.932143,0.039013
3,CZ-420820-24-12-0045,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,94961,False,55.816667,7.016667,6.015058,0.869295,-0.494293,0.038180
4,CZ-420820-23-06-0203,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,143695,False,57.933333,12.216667,11.039014,0.964961,-0.262392,0.037338
5,CZ-420820-24-09-0112,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,False,1,2,...,False,False,154253,False,15.950000,13.416667,22.280630,-0.169130,-0.985594,0.036465
6,CZ-420820-24-04-0170,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,157839,False,33.616667,12.050000,24.071184,0.627806,-0.778370,0.036421
7,CZ-420820-23-09-0002,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,123988,False,15.266667,8.183333,9.932923,0.960061,-0.279790,0.036388
8,CZ-420820-24-10-0043,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,138975,False,11.816667,8.633333,19.260780,0.339567,-0.940582,0.036050
9,CZ-420820-24-03-0192,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,71564,False,22.066667,16.100000,9.242984,0.915265,-0.402852,0.034682
10,CZ-450111-22-09-0038,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.0 10/2021,True,True,1,2,...,False,False,131406,False,8.666667,8.266667,7.282683,0.603048,-0.797705,0.034668
11,CZ-420820-23-07-0033,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,190647,False,95.200000,14.600000,20.892539,0.951402,-0.307953,0.034462
12,CZ-470118-22-05-0369,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,182622,False,13.166667,10.550000,19.783710,0.175113,-0.984548,0.034376
13,CZ-470118-25-02-0108,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS560,1.1,True,True,1,2,...,False,False,76892,False,17.316667,15.966667,20.739220,-0.243780,-0.969831,0.033506
14,CZ-470118-25-10-0270,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS560,1.1,True,True,1,2,...,False,False,121067,False,14.483333,12.900000,15.986311,0.745124,-0.666926,0.033170
15,CZ-470118-22-11-0127,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,10749,False,12.200000,8.483333,4.043806,0.793798,-0.608181,0.033039
16,CZ-470118-22-12-0089,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,227061,False,11.166667,9.033333,20.339493,0.840360,-0.542028,0.032375
17,CZ-450111-19-03-0150,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.5 08/2018,True,True,1,2,...,False,False,52832,False,6.400000,5.983333,3.986311,-0.311126,-0.950369,0.032356
18,CZ-470118-22-09-0225,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,False,1,2,...,False,False,211959,False,10.266667,8.216667,15.958932,0.750351,-0.661039,0.031970
19,CZ-470118-25-01-0115,Bosch,BEA070,BEA070 V1.19 CFFE0424,KTS560,1.1,True,True,1,2,...,False,False,296892,False,19.916667,18.600000,20.465435,0.105393,-0.994431,0.031503
20,CZ-420820-25-08-0340,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V3.0.5 01/2025,True,True,1,2,...,False,False,172958,False,11.283333,8.566667,16.240931,0.642730,-0.766093,0.031327
21,CZ-450111-19-06-0102,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.5 08/2018,True,True,1,2,...,False,False,87172,False,6.300000,5.650000,13.982204,0.578991,-0.815334,0.031236
22,CZ-470118-24-04-0313,Bosch,BEA 950,/ BEA070 V1.19 CFFE0424,KTS540,1.0,True,True,1,2,...,False,False,375650,False,14.433333,11.933333,17.549624,-0.246787,-0.969070,0.031026
23,CZ-470118-23-03-0145,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,149788,False,12.600000,10.716667,7.331964,0.844931,-0.534875,0.030816
24,CZ-420820-23-09-0096,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,85140,False,17.716667,13.700000,15.772758,0.561668,-0.827363,0.030681
25,CZ-470118-23-10-0006,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,179746,False,10.516667,7.650000,19.893224,0.860310,-0.509771,0.030275
26,CZ-470118-24-05-0270,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,42135,False,11.000000,9.366667,7.890486,0.178000,-0.984030,0.030262
27,CZ-450111-19-02-0035,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.5 08/2018,True,True,1,2,...,False,False,248003,False,6.400000,5.933333,15.134839,0.267851,-0.963460,0.030155
28,CZ-450111-19-03-0116,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.5 08/2018,True,True,1,2,...,False,False,90030,False,11.016667,10.550000,13.976728,0.643077,-0.765802,0.030155
29,CZ-470403-20-01-0287,BOSCH,BEA070,SW-BEA-PC CZ V1.21,ano,CZ V1.21,True,True,1,2,...,False,False,399418,False,15.566667,15.066667,12.933607,-0.102297,-0.994754,0.029835
30,CZ-420820-24-05-0221,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,79788,False,41.083333,8.133333,7.975359,0.583185,-0.812339,0.029820
31,CZ-420820-23-10-0248,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,94554,False,24.766667,11.166667,6.666667,0.714068,-0.700076,0.029717
32,CZ-470118-25-09-0045,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS560,1.1,True,True,1,2,...,False,False,211149,False,12.000000,10.483333,14.483231,0.078977,-0.996876,0.029283
33,CZ-470118-25-06-0353,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B,KTS560,1.1,True,False,1,2,...,False,False,174612,False,10.300000,8.983333,13.456537,0.999938,-0.011121,0.029258
34,CZ-471025-22-06-0276,Bosch,BEA 950,/ BEA070 V1.19 CFFE0424,KTS540,1.0,True,False,1,2,...,False,False,322349,False,11.800000,9.933333,17.002053,0.272474,-0.962163,0.029087
35,CZ-470118-23-02-0204,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,127474,False,13.100000,8.366667,17.872690,0.476847,-0.878986,0.029034
36,CZ-420820-23-09-0110,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,129109,False,63.416667,7.316667,7.978097,0.965630,-0.259919,0.029000
37,CZ-470118-22-06-0326,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,221391,False,10.266667,7.416667,14.001369,0.998468,-0.055329,0.028728
38,CZ-470118-24-11-0053,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,113499,False,10.733333,9.100000,16.112252,0.759149,-0.650917,0.028656
39,CZ-420820-25-08-0022,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V3.0.5 01/2025,True,True,1,2,...,False,False,183942,False,56.783333,11.800000,10.729637,0.740339,-0.672233,0.028590
40,CZ-470118-22-04-0352,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,69795,False,11.583333,8.133333,14.650240,0.846607,-0.532219,0.028404
41,CZ-450111-19-01-0097,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.4.5 08/2018,True,True,1,2,...,False,False,122125,False,6.233333,5.833333,14.184805,0.721981,-0.691913,0.028265
42,CZ-450111-22-08-0145,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.0 10/2021,True,True,1,2,...,False,False,205311,False,10.533333,9.983333,20.150582,0.459199,-0.888333,0.028209
43,CZ-420820-24-01-0047,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,135280,False,20.833333,15.350000,12.093087,0.737142,-0.675738,0.028180
44,CZ-420820-23-01-0132,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,114606,False,35.950000,8.883333,11.945243,0.570790,-0.821096,0.027659
45,CZ-470118-22-08-0358,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,53130,False,9.716667,6.900000,6.034223,-0.347943,-0.937516,0.027565
46,CZ-470118-22-06-0373,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,92274,False,10.300000,8.350000,6.151951,0.902977,-0.429690,0.027388
47,CZ-470118-23-03-0231,Bosch,BEA450_460,BEA V2.02-Mobil 38710554 / AMM 000-B6 F54B /,KTS540,1.0,True,True,1,2,...,False,False,57509,False,8.533333,7.133333,15.912389,0.957790,-0.287468,0.026889
48,CZ-450111-22-08-0117,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.0 10/2021,True,True,1,2,...,False,False,198423,False,8.666667,8.283333,18.858316,0.725799,-0.687907,0.026870
49,CZ-420820-24-11-0112,AVL DiTEST GmbH,AVL Gas 1000,V1.41 10/2014,AVL OBD 1000,V2.5.2 09/2022,True,True,1,2,...,False,False,144628,False,32.983333,21.366667,18.294319,0.704976,-0.709231,0.026535

# Anomalie
- rucni zadani
- bez OBD

In [18]:
short_display(df.filter(pl.col('Benzin_PocetVyusteni') == 1).filter(~pl.any_horizontal(pl.col(rucni_cols) == True)))

(0, 223)

Empty DataFrame
Columns: [CisloProtokolu, MericiPristroj_Vyrobce, MericiPristroj_Typ, MericiPristroj_Verze, MericiPristroj_OBD, MericiPristroj_VerzeSoftware, Vysledek_VisualniKontrola, Vysledek_Readiness, Vysledek_RidiciJednotkaStav, Vysledek_Mil, Obd_Readiness_Vysledek, Zavady, Poznamky, EmisniSystem, Obd_KomunikacniProtokol, Obd_KontrolaMil, Obd_PocetDtc, Obd_VypisDtc, Obd_VzdalenostDtc, Obd_CasDtc, Obd_Readiness_Zazeh_AC_Otestovano, Obd_Readiness_Zazeh_AC_Podporovano, Obd_Readiness_Zazeh_CAT-FUNC_Otestovano, Obd_Readiness_Zazeh_CAT-FUNC_Podporovano, Obd_Readiness_Zazeh_COMP_Otestovano, Obd_Readiness_Zazeh_COMP_Podporovano, Obd_Readiness_Zazeh_EGR-VVT_Otestovano, Obd_Readiness_Zazeh_EGR-VVT_Podporovano, Obd_Readiness_Zazeh_EVAP_Otestovano, Obd_Readiness_Zazeh_EVAP_Podporovano, Obd_Readiness_Zazeh_FUEL_Otestovano, Obd_Readiness_Zazeh_FUEL_Podporovano, Obd_Readiness_Zazeh_HCAT_Otestovano, Obd_Readiness_Zazeh_HCAT_Podporovano, Obd_Readiness_Zazeh_MISF_Otestovano, Obd_Readiness_Zazeh_MISF_Podporovano, Obd_Readiness_Zazeh_O2S-FUNC_Otestovano, Obd_Readiness_Zazeh_O2S-FUNC_Podporovano, Obd_Readiness_Zazeh_O2S-HEAT_Otestovano, Obd_Readiness_Zazeh_O2S-HEAT_Podporovano, Obd_Readiness_Zazeh_SAS_Otestovano, Obd_Readiness_Zazeh_SAS_Podporovano, Obd_Readiness_Vznet_AC_Otestovano, Obd_Readiness_Vznet_AC_Podporovano, Obd_Readiness_Vznet_BOOST_Otestovano, Obd_Readiness_Vznet_BOOST_Podporovano, Obd_Readiness_Vznet_COMP_Otestovano, Obd_Readiness_Vznet_COMP_Podporovano, Obd_Readiness_Vznet_DPF_Otestovano, Obd_Readiness_Vznet_DPF_Podporovano, Obd_Readiness_Vznet_EGR-VVT_Otestovano, Obd_Readiness_Vznet_EGR-VVT_Podporovano, Obd_Readiness_Vznet_EGS_Otestovano, Obd_Readiness_Vznet_EGS_Podporovano, Obd_Readiness_Vznet_FUEL_Otestovano, Obd_Readiness_Vznet_FUEL_Podporovano, Obd_Readiness_Vznet_MISF_Otestovano, Obd_Readiness_Vznet_MISF_Podporovano, Obd_Readiness_Vznet_NMHC_Otestovano, Obd_Readiness_Vznet_NMHC_Podporovano, Obd_Readiness_Vznet_NOX_Otestovano, Obd_Readiness_Vznet_NOX_Podporovano, Obd_Readiness_Vznet_RESERVE_Otestovano, Obd_Readiness_Vznet_RESERVE_Podporovano, Benzin_PocetVyusteni, Benzin_OtackyVolnobezne_CO2_Hodnota, Benzin_OtackyVolnobezne_CO2_Vysledek, Benzin_OtackyVolnobezne_COCOOR_Hodnota, Benzin_OtackyVolnobezne_COCOOR_Vysledek, Benzin_OtackyVolnobezne_CO_Hodnota, Benzin_OtackyVolnobezne_CO_Max_Hodnota, Benzin_OtackyVolnobezne_CO_Max_RucniZadani, Benzin_OtackyVolnobezne_CO_Vysledek, Benzin_OtackyVolnobezne_HC_Hodnota, Benzin_OtackyVolnobezne_HC_Max_Hodnota, Benzin_OtackyVolnobezne_HC_Max_RucniZadani, Benzin_OtackyVolnobezne_HC_Vysledek, Benzin_OtackyVolnobezne_LAMBDA_Hodnota, Benzin_OtackyVolnobezne_LAMBDA_Max_Hodnota, Benzin_OtackyVolnobezne_LAMBDA_Max_RucniZadani, Benzin_OtackyVolnobezne_LAMBDA_Min_Hodnota, Benzin_OtackyVolnobezne_LAMBDA_Min_RucniZadani, Benzin_OtackyVolnobezne_LAMBDA_Vysledek, Benzin_OtackyVolnobezne_NOX_Hodnota, Benzin_OtackyVolnobezne_NOX_Vysledek, Benzin_OtackyVolnobezne_N_Hodnota, Benzin_OtackyVolnobezne_N_Max_Hodnota, Benzin_OtackyVolnobezne_N_Max_RucniZadani, Benzin_OtackyVolnobezne_N_Min_Hodnota, Benzin_OtackyVolnobezne_N_Min_RucniZadani, Benzin_OtackyVolnobezne_N_Vysledek, Benzin_OtackyVolnobezne_O2_Hodnota, Benzin_OtackyVolnobezne_O2_Vysledek, Benzin_OtackyVolnobezne_TPS_Hodnota, Benzin_OtackyVolnobezne_TPS_Vysledek, Benzin_OtackyZvysene_CO2_Hodnota, Benzin_OtackyZvysene_CO2_Vysledek, Benzin_OtackyZvysene_COCOOR_Hodnota, Benzin_OtackyZvysene_COCOOR_Vysledek, Benzin_OtackyZvysene_CO_Hodnota, ...]
Index: []

[0 rows x 223 columns]